### ISSUE TITLE
Is "train+test" still valid as a key for split?

### ISSUE THREAD

**Issue by shun-lin** [tensorflow/datasets#1137]
**Short description**
Description of the bug.
 
```omniglot_data = tfds.load('omniglot', split="train+test")``` appears to be broken as "train+test" is an invalid split, but based on the documentation on tensorflow.org, https://www.tensorflow.org/datasets/splits, it should be valid.

**Environment information**
* Operating System: glinux
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: 1.3.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.0.0

**Reproduction instructions**

```
omniglot_data = tfds.load('omniglot', split="train+test")
```

**Link to logs**
Traceback (most recent call last):
  File "omniglot.py", line 239, in <module>
    app.run(main)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "omniglot.py", line 224, in main
    data = read_omniglot_data()
  File "omniglot.py", line 57, in read_omniglot_data
    omniglot_data = tfds.load('omniglot', split="train+test")
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 314, in load
    ds = dbuilder.as_dataset(**as_dataset_kwargs)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/wrapt/wrappers.py", line 603, in __call__
    args, kwargs)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 420, in as_dataset
    datasets = utils.map_nested(build_single_dataset, split, map_tuple=True)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 159, in map_nested
    return function(data_struct)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 479, in _build_single_dataset
    split=split, shuffle_files=shuffle_files, decoders=decoders)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 821, in _as_dataset
    read_instruction = split.get_read_instruction(self.info.splits)
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/splits.py", line 359, in get_read_instruction
    return SplitReadInstruction(split_dict[self._name])
  File "/usr/local/google/home/shunlin/similarity/similiarity_env/lib/python3.7/site-packages/tensorflow_datasets/core/splits.py", line 534, in __getitem__
    key, sorted(list(self.keys()))))
KeyError: "Invalid split train+test. Available splits are: ['small1', 'small2', 'test', 'train']"

**Expected behavior**
I expect that it would return a train and test concatenated data set.

**Additional context**

**Comment by Conchylicultor** [comment]
Only the last (non-default) version of omniglot support the new split API. To use it: `tfds.load('omniglot/3.0.0')`.
We plan to switch all datasets to the new default at once all datasets have been converted.

**Comment by shun-lin** [comment]
@Conchylicultor thank you so much for your quick response! Thank you!

**Comment by shun-lin** [comment]
@Conchylicultor when I ran ```tfds.load('omniglot/3.0.0')``` on Colab it gives me the following error

ERROR:absl:Failed to construct dataset omniglot
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-efab314d8ed9> in <module>()
----> 1 omniglot_test = tfds.load(name="omniglot/3.0.0")

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py in _create_builder_config(self, builder_config)
    670       if builder_config is None:
    671         raise ValueError("BuilderConfig %s not found. Available: %s" %
--> 672                          (name, list(self.builder_configs.keys())))
    673     name = builder_config.name
    674     if not name:

ValueError: BuilderConfig 3.0.0 not found. Available: []

Colab Env: tf 2.0, tfds 1.3.0

**Comment by Conchylicultor** [comment]
`tfds.load('omniglot:3.0.0')`, sorry.

**Comment by shun-lin** [comment]
oh got it, thanks @Conchylicultor!

**Comment by Conchylicultor** [comment]
Closing as this should be working now. We'll try to deprecate the legacy split as soon as possible so it won't be an issue anymore.
