### ISSUE TITLE
attributes() got an unexpected keyword argument 'frozen'

### ISSUE THREAD

**Issue by yhao2014** [tensorflow/datasets#1321]
**Short description**
when I am running code `import tensorflow_datasets as tfds`, the error appear as follow: 

**Environment information**
* Operating System: windows 10
* Python version: 3.6.5
* `tensorflow-datasets`/`tfds-nightly` version: 1.3.2
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.0.0

**Reproduction instructions**

```
Traceback (most recent call last):
  File "<input>", line 14, in <module>
  File "D:\Program Files\JetBrains\PyCharm 2019.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\conda\envs\LearningTensorflow\lib\site-packages\tensorflow_datasets\__init__.py", line 46, in <module>
    from tensorflow_datasets.core import tf_compat
  File "D:\Program Files\JetBrains\PyCharm 2019.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\conda\envs\LearningTensorflow\lib\site-packages\tensorflow_datasets\core\__init__.py", line 25, in <module>
    from tensorflow_datasets.core.dataset_builder import BeamBasedBuilder
  File "D:\Program Files\JetBrains\PyCharm 2019.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\conda\envs\LearningTensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 41, in <module>
    from tensorflow_datasets.core import tfrecords_reader
  File "D:\Program Files\JetBrains\PyCharm 2019.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\conda\envs\LearningTensorflow\lib\site-packages\tensorflow_datasets\core\tfrecords_reader.py", line 232, in <module>
    @attr.s(frozen=True)
TypeError: attributes() got an unexpected keyword argument 'frozen'
```

**Comment by Conchylicultor** [comment]
This likely indicates that you're using an old version of `attr`. Try to update the version with `pip`

**Comment by yhao2014** [comment]
> This likely indicates that you're using an old version of `attr`. Try to update the version with `pip`

I updated the module `attr` to 19.3.0, but it does not work any way.

**Comment by Conchylicultor** [comment]
`@attr.s(frozen=True)` is a documented value in: https://www.attrs.org/en/stable/api.html#attr.s

Are you sure you're not using a virtual environment which has a different version of attrs ? Can you try to `print(attrs.__version__)` in your code ?

**Comment by yhao2014** [comment]
> `@attr.s(frozen=True)` is a documented value in: https://www.attrs.org/en/stable/api.html#attr.s
> 
> Are you sure you're not using a virtual environment which has a different version of attrs ? Can you try to `print(attrs.__version__)` in your code ?

I solved this question by updating all Depended packages，thanks for your answer.
