### ISSUE TITLE
Got error when trying to add a new dataset in tfds

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1521]
Hey ! I am getting some error when I am following this instruction by tensorflow on [here ](https://www.tensorflow.org/datasets/add_dataset#overview)

After cloning repository I am run this code 
`python tensorflow_datasets/scripts/create_new_dataset.py \
  --dataset my_dataset \
  --type image  # text, audio, translation,...`

And Got error : 

> Traceback (most recent call last):
  File "tensorflow_datasets/scripts/create_new_dataset.py", line 241, in <module>
    app.run(main)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tensorflow_datasets/scripts/create_new_dataset.py", line 222, in main
    dataset_cls=naming.snake_to_camelcase(dataset_name),
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\core\naming.py", line 37, in snake_to_camelcase
    return "".join(n.capitalize() for n in name.split("_"))
AttributeError: 'NoneType' object has no attribute 'split'

How to resolve it.

**Comment by vijayphoenix** [comment]
Try running this command
```
python tensorflow_datasets/scripts/create_new_dataset.py --dataset my_dataset --type image
```

**Comment by Eshan-Agarwal** [comment]
Yeah I done that and after running it says search for TODO(mydataset) where to find it ?

**Comment by vijayphoenix** [comment]
See your output log.

Most probably this will be the path

```
C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\image\
```

**Comment by Eshan-Agarwal** [comment]
No I found mydataset.txt in url_checksums.

**Comment by vijayphoenix** [comment]
`mydataset.txt`, `my_dataset.py` `mydataset_test.py` all are different files.

I gave you the possible file path of  `my_dataset.py` and `mydataset_test.py` files

Which file do you want?

**Comment by Eshan-Agarwal** [comment]
Hey thanks for helping I got another error don't understand it. I make my_dataset.py and my_dataset_test.py file and update it in __init__.p also which is in Image directory also create mydataset.txt as mentioned now when I am trying this code
`# default data_dir is ~/tensorflow_datasets
python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=my_new_dataset`

I got error

> Traceback (most recent call last):
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\scripts\download_and_prepare.py", line 219, in <module>
    app.run(main)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\scripts\download_and_prepare.py", line 184, in main
    for name in datasets_to_build
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\scripts\download_and_prepare.py", line 184, in <dictcomp>
    for name in datasets_to_build
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\core\registered.py", line 172, in builder
    return _DATASET_REGISTRY[name](**builder_kwargs)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\translate\wmt.py", line 630, in __init__
    "The raw `wmt_translate` can only be instantiated with the config "
ValueError: The raw `wmt_translate` can only be instantiated with the config kwargs. You may want to use one of the `wmtYY_translate` implementation instead to get the WMT dataset for a specific year.

**Comment by vijayphoenix** [comment]
Please reopen the issue, so even other people can help you out.

**Comment by Eshan-Agarwal** [comment]
I think there is some version problem. How to decide right version for dataset ?

**Comment by vijayphoenix** [comment]
When implementing a new dataset, you can keep the version of dataset equal to `1.0.0`

**Comment by Eshan-Agarwal** [comment]
There is some problem in cogiguraton of wmt_translate while I am run download_and_prepare locally using 
 `# default data_dir is ~/tensorflow_datasets
python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=my_new_dataset`

but get this error

> Traceback (most recent call last):
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\scripts\download_and_prepare.py", line 219, in <module>
    app.run(main)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\scripts\download_and_prepare.py", line 184, in main
    for name in datasets_to_build
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\scripts\download_and_prepare.py", line 184, in <dictcomp>
    for name in datasets_to_build
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\core\registered.py", line 172, in builder
    return _DATASET_REGISTRY[name](**builder_kwargs)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\translate\wmt.py", line 630, in __init__
    "The raw `wmt_translate` can only be instantiated with the config "
ValueError: The raw `wmt_translate` can only be instantiated with the config kwargs. You may want to use one of the `wmtYY_translate` implementation instead to get the WMT dataset for a specific year.
