### ISSUE TITLE
Extending tfds builders to include Pix3D dataset

### ISSUE THREAD

**Issue by MadhavEsDios** [tensorflow/datasets#1610]
**What I need help with / What I was wondering**
I am currently attempting to extend tfds to include the Pix3D dataset as part of a potential GSoc'20 proposal in which the main motive is to implement MeshRCNN.
Dataset Link: [http://pix3d.csail.mit.edu/](url)

**What I've tried so far**
I have looked at the "Adding a dataset" documentation provided and tried to implement a builder to incorporate information from the Pix3D dataset. Link to script: [https://github.com/MadhavEsDios/tfds-pix3d/blob/master/pix3d.py](url)

**Issues I faced**

1. **Documentation for using manually downloaded datasets**
I first tried using the manual_dir option provided by dl_manager in the split_generators method. So I first downloaded the Pix3D dataset and extracted it to a local address. I then tried passing this local address to split_generators as follows: `extracted_path = dl_manager.manual_dir.manual_dir("/Users/Madhav/Experiments/meshrcnn/pix3d")`.
However, this kept throwing the same error of no dataset being present at the default location of `~/tensorflow_datasets/manual/..`. 
After some investigation, I found out that the  **MANUAL_DOWNLOAD_INSTRUCTIONS** has to be set to a "non-null" value for the manual_dir address check to take place in the `_make_download_manager` method. Setting this flag too did not work unfortunately as the download_config does not reflect the manual_dir info. 
Ultimately, I had to pass the download_config explicitly while calling the `pix3dbuilder.download_and_prepare(download_config=tfds.download.DownloadConfig(manual_dir="/Users/Madhav/Experiments/meshrcnn"))
`
It would be great if the documentation for using manually downloaded datasets could be a bit clearer. _I am open to submitting a pull request for tweaking the documentation unless I have ignored some important piece of information_

2. **Boolean / Null features** 
Is there a feature to accept boolean / None values? I am not sure about the importance of such a feature, however, some of the metadata in the Pix3D dataset had boolean/null values and using the `tfds.Features.Text` feature throws an error.

3. **Too many files**
Once I managed to get the `download_and_prepare` method working for a few examples, I encounter a **too many files** error. Here is the error message I get, 

`Downloading and preparing dataset pix3d/0.1.0 (download: Unknown size, generated: Unknown size, total: Unknown size) to /Users/Madhav/tensorflow_datasets/pix3d/0.1.0...
463 examples [05:09,  1.55 examples/s]Traceback (most recent call last):
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/file_format_adapter.py", line 200, in incomplete_dir
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 340, in download_and_prepare
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1079, in _download_and_prepare
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 932, in _download_and_prepare
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1106, in _prepare_split
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_writer.py", line 204, in write
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/shuffle.py", line 225, in add
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/shuffle.py", line 211, in _add_to_mem_buffer
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/shuffle.py", line 205, in _add_to_bucket
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/shuffle.py", line 127, in add
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 106, in write
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 92, in _prewrite_check
tensorflow.python.framework.errors_impl.ResourceExhaustedError: /Users/Madhav/tensorflow_datasets/pix3d/0.1.0.incompleteTS93XR/bucket_1cd06556-330f-4458-b817-8cc8f638cac1_402.tmp; Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pix3d.py", line 115, in <module>
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 363, in download_and_prepare
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/contextlib.py", line 130, in __exit__
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_datasets/core/file_format_adapter.py", line 204, in incomplete_dir
  File "/Users/Madhav/opt/anaconda3/envs/meshrcnn/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 571, in delete_recursively_v2
tensorflow.python.framework.errors_impl.ResourceExhaustedError: /Users/Madhav/tensorflow_datasets/pix3d/0.1.0.incompleteTS93XR; Too many open files`

+++

My apologies for the long post, I can open a separate issue for each point, if required.
Thanks!

**Environment information**

* Operating System: Mac OS
* Python version: <3.7>
* `tensorflow-datasets`/`tfds-nightly` version: <2.1.0>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <tensorflow-cpu 2.1.0>

**Comment by ChanchalKumarMaji** [comment]
This `dataset` can be downloaded from the link. I think manual download is not required.

**Comment by MadhavEsDios** [comment]
I am sorry that did not address my queries. The final code should use the link directly ( as there is no password protection), however, I think that is irrelevant to the issues I have faced.

**Comment by cyfra** [comment]
Hey @MadhavEsDios 

Thanks for contributing to tfds ! to answer your questions:

1) When MANUAL_DOWNLOAD_INSTRUCTIONS are not set, you should have gotten this Exception:
https://github.com/tensorflow/datasets/blob/e4aa686a4d623464cc5861464c6fbee6f3152e17/tensorflow_datasets/core/download/download_manager.py#L383

For passing the argument to the download_and_prepare: 
If you have good ideas on how to improve the documentation - please send the Pull Request.


2) For booleans, you can use tf.bool
https://github.com/tensorflow/datasets/blob/e29f355bb4c3f5bd05721f34ba683391d5736f25/tensorflow_datasets/object_detection/voc.py#L175

3) Do you also get this error when running in colab ? How large is this dataset (in MB and in number of objects generated)?

**Comment by vijayphoenix** [comment]
Please feel free to reopen the issue
