### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'mode'

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1667]
#1666 In `scripts/replace_fake_images.py` - it raises error :

> Traceback (most recent call last):
  File "replace_fake_images.py", line 144, in <module>
    absl.app.run(main)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "replace_fake_images.py", line 140, in main
    rewrite_dir(FLAGS.fake_dir)
  File "replace_fake_images.py", line 133, in rewrite_dir
    rewrite_tar(root_dir, path)
  File "replace_fake_images.py", line 107, in rewrite_tar
    rewrite_dir(temp_dir)  # Recursivelly compress the archive content
  File "replace_fake_images.py", line 133, in rewrite_dir
    rewrite_tar(root_dir, path)
  File "replace_fake_images.py", line 107, in rewrite_tar
    rewrite_dir(temp_dir)  # Recursivelly compress the archive content
  File "replace_fake_images.py", line 126, in rewrite_dir
    rewrite_image(path)
  File "replace_fake_images.py", line 49, in rewrite_image
    if image.mode == 'RGBA' or image.dtype == np.bool:
AttributeError: 'numpy.ndarray' object has no attribute 'mode'

**Comment by Conchylicultor** [comment]
Thank you for reporting. I think it should be the `PIL.Image().mode` instead of `np.array().mode`.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  yes it is replaced by `PIL.Image.open(filepath)` instead of `np.array().mode`.

**Comment by Conchylicultor** [comment]
Closing this as this has been fixed
