### ISSUE TITLE
[data request] ChestXray

### ISSUE THREAD

**Issue by ChanchalKumarMaji** [tensorflow/datasets#1688]
* Name of dataset: `ChestXray`
* URL of dataset: https://nihcc.app.box.com/v/ChestXray-NIHCC
* License of dataset: 
* Short description of dataset and use case(s): https://arxiv.org/abs/1705.02315

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by kabirwalia8300** [comment]
Hey I'd like to work on adding this dataset

**Comment by ChanchalKumarMaji** [comment]
> Hey I'd like to work on adding this dataset

Thank you ! :smiley: . Go ahead !

**Comment by kabirwalia8300** [comment]
Hey I was facing a problem with create_new_dataset.py. As I was getting the error
**ModuleNotFoundError: No module named 'tensorflow_datasets'**
I followed the suggestion in #1544 
But I continue to get the following error

**Traceback (most recent call last):
  File "tensorflow_datasets/scripts/create_new_dataset.py", line 38, in <module>
    from tensorflow_datasets.core import naming  # pylint: disable=g-import-not-at-top
  File "./tensorflow_datasets/__init__.py", line 47, in <module>
    from tensorflow_datasets.core import tf_compat
  File "./tensorflow_datasets/core/__init__.py", line 26, in <module>
    from tensorflow_datasets.core.dataset_builder import BeamBasedBuilder
  File "./tensorflow_datasets/core/dataset_builder.py", line 37, in <module>
    from tensorflow_datasets.core import download
  File "./tensorflow_datasets/core/download/__init__.py", line 20, in <module>
    from tensorflow_datasets.core.download.download_manager import DownloadConfig
  File "./tensorflow_datasets/core/download/download_manager.py", line 34, in <module>
    from tensorflow_datasets.core.download import downloader
  File "./tensorflow_datasets/core/download/downloader.py", line 32, in <module>
    import promise
ModuleNotFoundError: No module named 'promise'**

Haven't seen this elsewhere so I was wondering if someone could suggest what I was doing wrong.

**Comment by preeti13456** [comment]
Want to contribute

**Comment by preeti13456** [comment]
Data Exploration to be done with or without keras?

**Comment by vijayphoenix** [comment]
@preeti13456 yes, you can use keras.
For any external dependence read [tfds.core.lazy_imports](https://www.tensorflow.org/datasets/add_dataset#extra_dependencies)

**Comment by preeti13456** [comment]
Done
https://github.com/preeti13456/Projects-and-research/blob/master/GsocTensorflow.ipynb

**Comment by hrishikeshmane** [comment]
I am working on CheXNet right now. Might as well add the dataset to TFDS as a part of my GSOC project.

**Comment by jason-zl190** [comment]
@ChanchalKumarMaji I pulled a request of this dataset - #2041, please take a look. Any comments and reviews are also welcome.
