### ISSUE TITLE
tfds doesn't work

### ISSUE THREAD

**Issue by colinbebrave** [tensorflow/datasets#1695]
tfds just doesn't work..
every time I run code like 
`tfds.load('ted_hrlr_translate/pt_to_en', with_info=True)`, it would return 

```
ERROR:absl:Failed to construct dataset ted_hrlr_translate
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 305, in get_connection
    proxy_url = parse_url(proxy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/util/url.py", line 398, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
export
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 302, in load
    dbuilder = builder(name, data_dir=data_dir, **builder_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 172, in builder
    return _DATASET_REGISTRY[name](**builder_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 203, in __init__
    self.info.initialize_from_bucket()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_info.py", line 428, in initialize_from_bucket
    data_files = gcs_utils.gcs_dataset_info_files(self.full_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/utils/gcs_utils.py", line 65, in gcs_dataset_info_files
    filenames = [el for el in gcs_files(prefix_filter=prefix)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/utils/gcs_utils.py", line 55, in gcs_files
    top_level_xml_str = download_gcs_file("", prefix_filter=prefix_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_datasets/core/utils/gcs_utils.py", line 41, in download_gcs_file
    resp = requests.get(url, stream=stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 414, in send
    raise InvalidURL(e, request=request)
export
```

**What I've tried so far**
I upgraded tfds, six, requests, but still no gains.

**Environment information**
* Operating System: macos 10.15.3
* Python version: 3.7.3
* `tensorflow-datasets`/`tfds-nightly` version: 2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.1.0

**Comment by Eshan-Agarwal** [comment]
@colinbebrave  I think there is something wrong in your setup try to re-install things. Please refer this [colab ](https://colab.research.google.com/drive/1-xXtcQnsMBnBrQFBoOZHUmMwaTTgckqC)its work fine

**Comment by Eshan-Agarwal** [comment]
Please try to re-install `absl` its work fine on local also

**Comment by colinbebrave** [comment]
> Please try to re-install `absl` its work fine on local also

I updated all python packages, but tdfs still kept giving the same warning..

**Comment by Eshan-Agarwal** [comment]
Please create new environment and then after installing all dependencies again try it. Is it works fine in colab as i given ?

**Comment by colinbebrave** [comment]
> Please create new environment and then after installing all dependencies again try it. Is it works fine in colab as i given ?

hey Eshan, thanks a lot, I just solved the problem,  check here https://github.com/psf/requests/issues/4613,
i configured the proxy, and there was some illegal characters in proxy configuration. 
I am closing this issue.
