### ISSUE TITLE
TFDS Librispeech cannot generate TFRecord files

### ISSUE THREAD

**Issue by nicolasshu** [tensorflow/datasets#2015]
**Short description**
I have downloaded the entire dataset and I expected to make the TF Record files, but the code described by the documentation seems to crash while reading a JSON object, which I'm not sure which one. I'm not sure what else to do

**Environment information**
* Operating System: Ubuntu 18.04
* Python version: Python 3.6
* `tensorflow-datasets`/`tfds-nightly` version: `tensorflow-datasets 3.1.0`
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: `tensorflow 2.1`

**Reproduction instructions**

```
python -m tensorflow_datasets.scripts.download_and_prepare --datasets=librispeech
```

**Logs**

```
2020-05-11 22:24:52.153303: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not 
load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No s
uch file or directory; LD_LIBRARY_PATH: /usr/lib64/mpich/lib:/usr/local/cuda/lib64:/usr/local/cuda/ext
ras/CUPTI/lib64
2020-05-11 22:24:52.156487: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not 
load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared obj
ect file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/mpich/lib:/usr/local/cuda/lib64:/usr/
local/cuda/extras/CUPTI/lib64
2020-05-11 22:24:52.156569: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some
 TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing l
ibraries mentioned above are installed properly.
I0511 22:25:18.148408 140253212075840 download_and_prepare.py:194] Running download_and_prepare for da
taset(s):
librispeech
I0511 22:25:18.152765 140253212075840 dataset_builder.py:776] No config specified, defaulting to first
: librispeech/plain_text
I0511 22:25:18.385578 140253212075840 dataset_info.py:430] Load pre-computed DatasetInfo (eg: splits, 
num examples,...) from GCS: librispeech/plain_text/1.1.0
I0511 22:25:18.852972 140253212075840 dataset_info.py:361] Load dataset info from /tmp/tmp2sl_438etfds
I0511 22:25:18.897377 140253212075840 dataset_info.py:401] Field info.description from disk and from c
ode do not match. Keeping the one from code.
I0511 22:25:18.897629 140253212075840 dataset_info.py:401] Field info.citation from disk and from code
 do not match. Keeping the one from code.
I0511 22:25:18.905071 140253212075840 dataset_info.py:430] Load pre-computed DatasetInfo (eg: splits, 
num examples,...) from GCS: librispeech/plain_text/1.1.0
I0511 22:25:19.422953 140253212075840 dataset_info.py:361] Load dataset info from /tmp/tmpk_x7qnhmtfds
I0511 22:25:19.469963 140253212075840 dataset_info.py:401] Field info.description from disk and from c
ode do not match. Keeping the one from code.
I0511 22:25:19.470215 140253212075840 dataset_info.py:401] Field info.citation from disk and from code
 do not match. Keeping the one from code.
I0511 22:25:19.470832 140253212075840 download_and_prepare.py:133] download_and_prepare for dataset li
brispeech/plain_text/1.1.0...
I0511 22:25:23.255491 140253212075840 dataset_builder.py:333] Generating dataset librispeech (/home/ns
hu/tensorflow_datasets/librispeech/plain_text/1.1.0)
Downloading and preparing dataset librispeech/plain_text/1.1.0 (download: 57.14 GiB, generated: 304.47
 GiB, total: 361.62 GiB) to /home/nshu/tensorflow_datasets/librispeech/plain_text/1.1.0...
I0511 22:25:24.070286 140253212075840 pipeline.py:180] Missing pipeline option (runner). Executing pip
eline using the default runner: DirectRunner.
Dl Completed...: 0 url [00:00, ? url/s]          I0511 22:25:24.104006 140253212075840 download_manage
r.py:291] URL http://www.openslr.org/resources/12/dev-clean.tar.gz already downloaded: reusing /home/n
shu/tensorflow_datasets/downloads/openslr.org_resources_12_dev-cleandvh9CQZQYX_KDKyPiLlBbg6_gDUKy5ezQ6
hfqQNyirM.tar.gz.
I0511 22:25:24.108725 140253212075840 download_manager.py:324] Reusing extraction of /home/nshu/tensor
flow_datasets/downloads/openslr.org_resources_12_dev-cleandvh9CQZQYX_KDKyPiLlBbg6_gDUKy5ezQ6hfqQNyirM.
tar.gz at /home/nshu/tensorflow_datasets/downloads/extracted/TAR_GZ.openslr.org_resources_12_dev-clean
dvh9CQZQYX_KDKyPiLlBbg6_gDUKy5ezQ6hfqQNyirM.tar.gz.
I0511 22:25:24.111679 140253212075840 download_manager.py:291] URL http://www.openslr.org/resources/12
/dev-other.tar.gz already downloaded: reusing /home/nshu/tensorflow_datasets/downloads/openslr.org_res
ources_12_dev-otherEmYcSOjD_h3iwcqkw-E1GTv7GBFYTxH1ad0SZFqoQ2U.tar.gz.
I0511 22:25:24.115045 140253212075840 download_manager.py:324] Reusing extraction of /home/nshu/tensor
flow_datasets/downloads/openslr.org_resources_12_dev-otherEmYcSOjD_h3iwcqkw-E1GTv7GBFYTxH1ad0SZFqoQ2U.
tar.gz at /home/nshu/tensorflow_datasets/downloads/extracted/TAR_GZ.openslr.org_resources_12_dev-other
EmYcSOjD_h3iwcqkw-E1GTv7GBFYTxH1ad0SZFqoQ2U.tar.gz.
I0511 22:25:24.117633 140253212075840 download_manager.py:291] URL http://www.openslr.org/resources/12
/test-clean.tar.gz already downloaded: reusing /home/nshu/tensorflow_datasets/downloads/openslr.org_re
sources_12_test-cleanOf3lJeWWctxtFVGRmxR49yRDipWqVfh0tXa-IZZ-bCM.tar.gz.
Dl Completed...: 0 url [00:00, ? url/s]                                                               
I0511 22:25:24.126044 140253212075840 download_manager.py:291] URL http://www.openslr.org/resources/12
/test-other.tar.gz already downloaded: reusing /home/nshu/tensorflow_datasets/downloads/openslr.org_re
sources_12_test-other0JwYG7pc9xez3ufU1ZKvEaPuOgngiuAlxVBvbr6WHCk.tar.gz.
I0511 22:25:24.129332 140253212075840 download_manager.py:324] Reusing extraction of /home/nshu/tensor
flow_datasets/downloads/openslr.org_resources_12_test-other0JwYG7pc9xez3ufU1ZKvEaPuOgngiuAlxVBvbr6WHCk
.tar.gz at /home/nshu/tensorflow_datasets/downloads/extracted/TAR_GZ.openslr.org_resources_12_test-oth
er0JwYG7pc9xez3ufU1ZKvEaPuOgngiuAlxVBvbr6WHCk.tar.gz.
I0511 22:25:24.132411 140253212075840 download_manager.py:291] URL http://www.openslr.org/resources/12
/train-clean-100.tar.gz already downloaded: reusing /home/nshu/tensorflow_datasets/downloads/openslr.o
rg_resource_12_train-clean-1001N3R1aarMDBm8Ulx12juQyeKXyoKpD3HFrDmTsu79uI.tar.gz.
I0511 22:25:24.135689 140253212075840 download_manager.py:324] Reusing extraction of /home/nshu/tensor
flow_datasets/downloads/openslr.org_resource_12_train-clean-1001N3R1aarMDBm8Ulx12juQyeKXyoKpD3HFrDmTsu
79uI.tar.gz at /home/nshu/tensorflow_datasets/downloads/extracted/TAR_GZ.openslr.org_resource_12_train
-clean-1001N3R1aarMDBm8Ulx12juQyeKXyoKpD3HFrDmTsu79uI.tar.gz.
I0511 22:25:24.138364 140253212075840 download_manager.py:291] URL http://www.openslr.org/resources/12
/train-clean-360.tar.gz already downloaded: reusing /home/nshu/tensorflow_datasets/downloads/openslr.o
rg_resource_12_train-clean-360FGpWSWIX6WwUM0oWDfl__-3W4KBOZrnFrw1Avjx5Ls8.tar.gz.
I0511 22:25:24.141838 140253212075840 download_manager.py:324] Reusing extraction of /home/nshu/tensor
flow_datasets/downloads/openslr.org_resource_12_train-clean-360FGpWSWIX6WwUM0oWDfl__-3W4KBOZrnFrw1Avjx
5Ls8.tar.gz at /home/nshu/tensorflow_datasets/downloads/extracted/TAR_GZ.openslr.org_resource_12_train
-clean-360FGpWSWIX6WwUM0oWDfl__-3W4KBOZrnFrw1Avjx5Ls8.tar.gz.
I0511 22:25:24.144939 140253212075840 download_manager.py:291] URL http://www.openslr.org/resources/12
/train-other-500.tar.gz already downloaded: reusing /home/nshu/tensorflow_datasets/downloads/openslr.o
rg_resource_12_train-other-5003bIvJ_luwWNkXVMhVVnfaqNlFfJuAd1weYGINQrcttI.tar.gz.
I0511 22:25:24.148357 140253212075840 download_manager.py:324] Reusing extraction of /home/nshu/tensor
flow_datasets/downloads/openslr.org_resource_12_train-other-5003bIvJ_luwWNkXVMhVVnfaqNlFfJuAd1weYGINQr
cttI.tar.gz at /home/nshu/tensorflow_datasets/downloads/extracted/TAR_GZ.openslr.org_resource_12_train
-other-5003bIvJ_luwWNkXVMhVVnfaqNlFfJuAd1weYGINQrcttI.tar.gz.
Dl Completed...: 0 url [01:14, ? url/s]
Extraction completed...: 100%|███████████████████████████████████████| 1/1 [01:14<00:00, 74.25s/ file]
Extraction completed...: 100%|███████████████████████████████████████| 1/1 [01:14<00:00, 74.25s/ file]
Dl Size...: 0 MiB [01:14, ? MiB/s]


Dl Completed...: 0 url [01:14, ? url/s]
I0511 22:26:38.633954 140253212075840 dataset_builder.py:924] Generating split dev_clean
I0511 22:26:39.186865 140253212075840 dataset_builder.py:924] Generating split dev_other
I0511 22:26:39.551187 140253212075840 dataset_builder.py:924] Generating split test_clean
I0511 22:26:39.911982 140253212075840 dataset_builder.py:924] Generating split test_other
I0511 22:26:40.264321 140253212075840 dataset_builder.py:924] Generating split train_clean100
I0511 22:26:40.616268 140253212075840 dataset_builder.py:924] Generating split train_clean360
I0511 22:26:40.982954 140253212075840 dataset_builder.py:924] Generating split train_other500
I0511 22:26:48.929174 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
annotate_downstream_side_inputs at 0x7f8ea0d509d8> ====================
I0511 22:26:48.938828 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
fix_side_input_pcoll_coders at 0x7f8ea0d50ae8> ====================
I0511 22:26:48.943548 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
lift_combiners at 0x7f8ea0d50b70> ====================
I0511 22:26:48.949277 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
expand_sdf at 0x7f8ea0d50bf8> ====================
I0511 22:26:48.953731 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
expand_gbk at 0x7f8ea0d50c80> ====================
I0511 22:26:48.961900 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
sink_flattens at 0x7f8ea0d50d90> ====================
I0511 22:26:48.967650 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
greedily_fuse at 0x7f8ea0d50e18> ====================
I0511 22:26:48.985618 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
read_to_impulse at 0x7f8ea0d50ea0> ====================
I0511 22:26:48.987317 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
impulse_to_input at 0x7f8ea0d50f28> ====================
I0511 22:26:48.989402 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
inject_timer_pcollections at 0x7f8ea0cd2158> ====================
I0511 22:26:48.993441 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
sort_stages at 0x7f8ea0cd21e0> ====================
I0511 22:26:48.994672 140253212075840 fn_api_runner_transforms.py:548] ==================== <function 
window_pcollection_coders at 0x7f8ea0cd2268> ====================
I0511 22:26:49.034509 140253212075840 statecache.py:154] Creating state cache with size 100
I0511 22:26:49.037167 140253212075840 fn_api_runner.py:2011] Created Worker handler <apache_beam.runne
rs.portability.fn_api_runner.EmbeddedWorkerHandler object at 0x7f8e92f86898> for environment urn: "bea
m:env:embedded_python:v1"

I0511 22:26:49.039396 140253212075840 fn_api_runner.py:974] Running ((((((ref_AppliedPTransform_train_
clean360/Create/Impulse_294)+(ref_AppliedPTransform_train_clean360/Create/FlatMap(<lambda at core.py:2
639>)_295))+(ref_AppliedPTransform_train_clean360/Create/Map(decode)_297))+(ref_AppliedPTransform_trai
n_clean360/FlatMap(_generate_librispeech_examples)_298))+(ref_AppliedPTransform_train_clean360/Reshuff
le/AddRandomKeys_300))+(ref_AppliedPTransform_train_clean360/Reshuffle/ReshufflePerKey/Map(reify_times
tamps)_302))+(train_clean360/Reshuffle/ReshufflePerKey/GroupByKey/Write)
I0511 22:43:57.257659 140253212075840 fn_api_runner.py:974] Running (((((train_clean360/Reshuffle/Resh
ufflePerKey/GroupByKey/Read)+(ref_AppliedPTransform_train_clean360/Reshuffle/ReshufflePerKey/FlatMap(r
estore_timestamps)_307))+(ref_AppliedPTransform_train_clean360/Reshuffle/RemoveRandomKeys_308))+(ref_A
ppliedPTransform_train_clean360/Encode_309))+(ref_AppliedPTransform_train_clean360/SerializeBucketize_
310))+(train_clean360/GroupByBucket/Write)
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 950, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 548, in apache_beam.runners.common.SimpleInvoker.invoke_p
rocess
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/transforms/core.py", l
ine 1446, in <lambda>
    wrapper = lambda x: [fn(x)]
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/dataset_b
uilder.py", line 1146, in <lambda>
    lambda key_ex: (key_ex[0], encode_example(key_ex[1])))
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
features_dict.py", line 170, in encode_example
    in utils.zip_dict(self._feature_dict, example_dict)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
features_dict.py", line 169, in <dictcomp>
    for k, (feature, example_value)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
audio_feature.py", line 76, in encode_example
    return self._encode_file(audio_f, file_format)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
audio_feature.py", line 64, in _encode_file
    fobj, format=file_format)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/pydub/audio_segment.py", line 670,
 in from_file
    info = mediainfo_json(orig_file)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/pydub/utils.py", line 272, in medi
ainfo_json
    info = json.loads(output)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/scripts/downlo
ad_and_prepare.py", line 234, in <module>
    app.run(main)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/absl/app.py", line 250, in _run_ma
in
    sys.exit(main(argv))
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/scripts/downlo
ad_and_prepare.py", line 225, in main
    download_and_prepare(builder_for_config)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/scripts/downlo
ad_and_prepare.py", line 150, in download_and_prepare
    download_config=dl_config,
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/api_utils
.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/dataset_b
uilder.py", line 363, in download_and_prepare
    download_config=download_config)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/dataset_b
uilder.py", line 1102, in _download_and_prepare
    pipeline=pipeline,
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/pipeline.py", line 503
, in __exit__
    self.run().wait_until_finish()
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/pipeline.py", line 483
, in run
    self._options).run(False)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/pipeline.py", line 496
, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/direct/direct_
runner.py", line 130, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 555, in run_pipeline
    pipeline.to_runner_api(default_environment=self._default_environment))
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 565, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 706, in run_stages
    stage_context.safe_coders)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 1073, in _run_stage
    result, splits = bundle_manager.process_bundle(data_input, data_output)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 2334, in process_bundle
    for result, split_result in executor.map(execute, part_inputs):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result
_iterator
    yield fs.pop().result()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_
result
    raise self._exception
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/utils/thread_pool_exec
utor.py", line 44, in run
    self._future.set_result(self._fn(*self._fn_args, **self._fn_kwargs))
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 2331, in execute
    return bundle_manager.process_bundle(part_map, expected_outputs)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 2245, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/portability/fn
_api_runner.py", line 1559, in push
    response = self.worker.do_instruction(request)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/worker/sdk_wor
ker.py", line 415, in do_instruction
    getattr(request, request_type), request.instruction_id)

  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/worker/sdk_wor
ker.py", line 450, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/worker/bundle_
processor.py", line 839, in process_bundle
    input_op_by_transform_id[data.transform_id].process_encoded(data.data)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/runners/worker/bundle_
processor.py", line 216, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 327, in apache_beam.runners.worker.operations.
Operation.output
  File "apache_beam/runners/worker/operations.py", line 329, in apache_beam.runners.worker.operations.
Operation.output
  File "apache_beam/runners/worker/operations.py", line 192, in apache_beam.runners.worker.operations.
SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 682, in apache_beam.runners.worker.operations.
DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 683, in apache_beam.runners.worker.operations.
DoOperation.process
  File "apache_beam/runners/common.py", line 952, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1013, in apache_beam.runners.common.DoFnRunner._reraise_a
ugmented
  File "apache_beam/runners/common.py", line 950, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 547, in apache_beam.runners.common.SimpleInvoker.invoke_p
rocess
  File "apache_beam/runners/common.py", line 1105, in apache_beam.runners.common._OutputProcessor.proc
ess_outputs
  File "apache_beam/runners/worker/operations.py", line 192, in apache_beam.runners.worker.operations.
SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 682, in apache_beam.runners.worker.operations.
DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 683, in apache_beam.runners.worker.operations.
DoOperation.process
  File "apache_beam/runners/common.py", line 952, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1013, in apache_beam.runners.common.DoFnRunner._reraise_a
ugmented
  File "apache_beam/runners/common.py", line 950, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 547, in apache_beam.runners.common.SimpleInvoker.invoke_p
rocess
  File "apache_beam/runners/common.py", line 1105, in apache_beam.runners.common._OutputProcessor.proc
ess_outputs
  File "apache_beam/runners/worker/operations.py", line 192, in apache_beam.runners.worker.operations.
SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 682, in apache_beam.runners.worker.operations.
DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 683, in apache_beam.runners.worker.operations.
DoOperation.process
  File "apache_beam/runners/common.py", line 952, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1028, in apache_beam.runners.common.DoFnRunner._reraise_a
ugmented
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/future/utils/__init__.py", line 44
6, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 950, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 548, in apache_beam.runners.common.SimpleInvoker.invoke_p
rocess
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/apache_beam/transforms/core.py", l
ine 1446, in <lambda>
    wrapper = lambda x: [fn(x)]
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/dataset_b
uilder.py", line 1146, in <lambda>
    lambda key_ex: (key_ex[0], encode_example(key_ex[1])))
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
features_dict.py", line 170, in encode_example
    in utils.zip_dict(self._feature_dict, example_dict)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
features_dict.py", line 169, in <dictcomp>
    for k, (feature, example_value)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
audio_feature.py", line 76, in encode_example
    return self._encode_file(audio_f, file_format)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/tensorflow_datasets/core/features/
audio_feature.py", line 64, in _encode_file
    fobj, format=file_format)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/pydub/audio_segment.py", line 670,
 in from_file
    info = mediainfo_json(orig_file)
  File "/home/nshu/virtualenvs/speech/lib64/python3.6/site-packages/pydub/utils.py", line 272, in medi
ainfo_json
    info = json.loads(output)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
RuntimeError: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) [while running '
train_clean360/Encode']

```

**Expected behavior**
I'd expect the PCollections to create the appropriate files for the usage of `tfds.load("librispeech")`

**Comment by ng390** [comment]
Were you able to resolve this issue? Did you use the beam DirectRunner?

**Comment by fineguy** [comment]
Nowadays you can use `tfds build librispeech/default` to build the dataset.
