### ISSUE TITLE
tarfile.ReadError: bad checksum ImageNet tensorflow dataset

### ISSUE THREAD

**Issue by martinmamql** [tensorflow/datasets#2087]
**What I need help with / What I was wondering**
Initialize checksum file when I have ILSVRC2012_img_train.tar and ILSVRC2012_img_val.tar

**What I've tried so far**
I have followed https://www.tensorflow.org/datasets/catalog/imagenet2012 and put the two archive files ILSVRC2012_img_train.tar and ILSVRC2012_img_val.tar to the corresponding directory. Then the error
`tarfile.ReadError: bad checksum`
occurs.
After adding the following lines to try to initialize the checksum file:
```
checksum_dir = os.path.join(os.path.dirname(__file__), '/home/martin_ma_mql/tensorflow_datasets/downloads/manual/checksu$
  checksum_dir = os.path.normpath(checksum_dir)
  # Add the checksum dir (will be executed when the user import your dataset)
  tfds.download.add_checksums_dir(checksum_dir)
  builder = tfds.builder(FLAGS.dataset, data_dir=FLAGS.data_dir)
  dl_config = tfds.download.DownloadConfig(register_checksums=True)
  builder.download_and_prepare(download_config=dl_config)
```

The error persists.

Full error message:
```
WARNING:tensorflow:From /home/martin_ma_mql/simclr/resnet.py:38: The name tf.layers.BatchNormalization is deprecated. Pleas
e use tf.compat.v1.layers.BatchNormalization instead.
I0615 02:39:01.717853 139708827453184 dataset_info.py:430] Load pre-computed DatasetInfo (eg: splits, num examples,...) fro
m GCS: imagenet2012/5.0.0
I0615 02:39:01.762809 139708827453184 dataset_info.py:361] Load dataset info from /tmp/tmpjzvgtj2_tfds
I0615 02:39:01.768465 139708827453184 dataset_info.py:401] Field info.description from disk and from code do not match. Kee
ping the one from code.
I0615 02:39:01.768634 139708827453184 dataset_info.py:401] Field info.citation from disk and from code do not match. Keepin
g the one from code.
I0615 02:39:01.769159 139708827453184 dataset_builder.py:333] Generating dataset imagenet2012 (/home/martin_ma_mql/tensorfl
ow_datasets/imagenet2012/5.0.0)
Downloading and preparing dataset imagenet2012/5.0.0 (download: 144.02 GiB, generated: Unknown size, total: 144.02 GiB) to 
/home/martin_ma_mql/tensorflow_datasets/imagenet2012/5.0.0...
I0615 02:39:08.569597 139708827453184 dataset_builder.py:924] Generating split train
Traceback (most recent call last):
  File "/usr/lib/python3.5/tarfile.py", line 2281, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.5/tarfile.py", line 1083, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.5/tarfile.py", line 1027, in frombuf
    raise InvalidHeaderError("bad checksum")
tarfile.InvalidHeaderError: bad checksum
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 427, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run.py", line 347, in main
    builder.download_and_prepare(download_config=dl_config)
  File "/home/martin_ma_mql/.local/lib/python3.5/site-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow
_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/martin_ma_mql/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_builder.py", line 363, in d
ownload_and_prepare
    download_config=download_config)
  File "/home/martin_ma_mql/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_builder.py", line 996, in _
download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/home/martin_ma_mql/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_builder.py", line 928, in _
download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/martin_ma_mql/.local/lib/python3.5/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1011, in 
_prepare_split
    total=split_info.num_examples, leave=False):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/martin_ma_mql/.local/lib/python3.5/site-packages/tensorflow_datasets/image_classification/imagenet.py", line 
195, in _generate_examples
    fobj_mem, tfds.download.ExtractMethod.TAR_STREAM):
  File "/home/martin_ma_mql/.local/lib/python3.5/site-packages/tensorflow_datasets/core/download/extractor.py", line 163, i
n iter_tar
    tar = tarfile.open(mode=read_type, fileobj=fobj)
  File "/usr/lib/python3.5/tarfile.py", line 1589, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.5/tarfile.py", line 2293, in next
    raise ReadError(str(e))
tarfile.ReadError: bad checksum
```

**It would be nice if...**
Since the official documentation says that we need to pre-download, after downloading step how may we proceed to initialize the checksum to avoid the error?

**Environment information**
(if applicable)
* Operating System: Debian GNU/Linux 9 on Google Cloud n1-standard-2
* Python version: 3.5.3
* `tensorflow-datasets`/`tfds-nightly` version: 3.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 1.15.2

Thank you so much for your great patience and help!

**Comment by Conchylicultor** [comment]
We haven't tested our code with Python 3.5. Could you try with 3.6+ ?

The error seems to be during the extraction of `/usr/lib/python3.5/tarfile.py`. Does the extraction works without TFDS ? It may indicate that the archive is corrupted.

**Comment by martinmamql** [comment]
Dear Conchylicultor,

Greetings! Sorry for the reply. It is indeed two corrupted files and I have resolved this by downloading again.

Thank you so much for your great help and feel free to close this issue!

Sincerely,
Martin

**Comment by mushan09** [comment]
@Conchylicultor @martinmamql 
I downloaded the original image before but I lost the tar files(ILSVRC2012_img_train.tar and ILSVRC2012_img_val.tar).
So I repackaged these original pictures into tar files and occured the same problem(bad checksum).

I want to know what conditions are used to verify the ImageNet dataset, and whether the verification can be skipped. Re-downloading ILSVRC2012_img_train.tar took too long for me.

Sincerely,
Steve

**Comment by martinmamql** [comment]
Hi Steve, sorry that I am not sure how to correctly verify the ImageNet dataset. But I would recommend a re-downloading since I used to try different methods, but eventually solve the problem by re-downloading.

I hope this might help.

Sincerely,
Martin

**Comment by mushan09** [comment]
Thank you Martin, I tried many methods but none of them worked. It took 2 days to download 20G.
I have no other ideas, so I will try again when the download is complete.

Thank you again for your help.

Sincerely,
Steve

**Comment by martinmamql** [comment]
Not a problem Steve! Good luck on your project.
