### ISSUE TITLE
the300w_lp dataset not loading with an error.

### ISSUE THREAD

**Issue by SamyakAgarkar** [tensorflow/datasets#2329]
I am trying to load the300w_lp datawset with

`import tensorflow_datasets as tfds`
`the300w, info = tfds.load('the300w_lp', data_dir='/downloadeddataset/the300', with_info=True)`

Causing the following error

>>> the300w, info = tfds.load('the300w_lp', data_dir='/downloadeddataset/the300', with_info=True)
Downloading and preparing dataset the300w_lp/1.0.0 (download: Unknown size, generated: Unknown size, total: Unknown size) to /downloadeddataset/the300\the300w_lp\1.0.0...
Dl Completed...: 0 url [00:00, ? url/s]
Extraction completed...: 0 file [00:00, ? file/s]
Extraction completed...: 0 file [00:00, ? file/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]

Dl Completed...: 0 url [00:00, ? url/s]
Shuffling and writing examples to /downloadeddataset/the300\the300w_lp\1.0.0.incompleteD1QFEF\the300w_lp-train.tfrecord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\registered.py", line 371, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 376, in download_and_prepare
    download_config=download_config)
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 1019, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 951, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 1037, in _prepare_split   
    shard_lengths, total_size = writer.finalize()
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\tfrecords_writer.py", line 213, in finalize
    self._shuffler.bucket_lengths, self._path)
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\tfrecords_writer.py", line 97, in _get_shard_specs  
    shard_boundaries = _get_shard_boundaries(num_examples, num_shards)
  File "C:\Users\SamyakAgarkar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\tfrecords_writer.py", line 120, in _get_shard_boundaries
    raise AssertionError("No examples were yielded.")
AssertionError: No examples were yielded.

Please help

**Comment by vijayphoenix** [comment]
Let us know if you still face any issue
