### ISSUE TITLE
Failed to construct dataset wmt_translateThe raw `wmt_translate` during download_and_prepare with --register_checksums

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/datasets#2379]
**Short description**
A `ValueError` is raised when trying to registering checksums.

**Environment information**
* Operating System: Arch Linux
* Python version: 3.8
* `tensorflow-datasets`/`tfds-nightly` version: 3.2.1-nightly
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow 2.3.0

**Reproduction instructions**

```
git clone https://github.com/tensorflow/datasets.git
cd datasets
pip install -e .
pip install tensorflow
python -m tensorflow_datasets.scripts.download_and_prepare --register_checksums --checksums_dir=./url_checksums
```

**Link to logs**

```console-output
Traceback (most recent call last):
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/core/utils/py_utils.py", line 420, in try_reraise
    yield
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/core/load.py", line 179, in builder
    return builder_cls(name)(**builder_kwargs)  # pytype: disable=not-instantiable
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/translate/wmt.py", line 625, in __init__
    raise ValueError(
ValueError: The raw `wmt_translate` can only be instantiated with the config kwargs. You may want to use one of the `wmtYY_translate` implementation instead to get the WMT dataset for a specific year.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/scripts/download_and_prepare.py", line 240, in <module>
    app.run(main)
  File "/home/ubik/.python_envs/tfds/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/ubik/.python_envs/tfds/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/scripts/download_and_prepare.py", line 201, in main
    builders = {
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/scripts/download_and_prepare.py", line 202, in <dictcomp>
    name: tfds.builder(name, data_dir=FLAGS.data_dir, **version_kwarg)
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/core/load.py", line 179, in builder
    return builder_cls(name)(**builder_kwargs)  # pytype: disable=not-instantiable
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/core/utils/py_utils.py", line 422, in try_reraise
    reraise(*args, **kwargs)
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/core/utils/py_utils.py", line 413, in reraise
    six.reraise(exc_type, exc_type(msg), exc_traceback)
  File "/home/ubik/.python_envs/tfds/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/core/utils/py_utils.py", line 420, in try_reraise
    yield
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/core/load.py", line 179, in builder
    return builder_cls(name)(**builder_kwargs)  # pytype: disable=not-instantiable
  File "/home/ubik/Documents/work/datasets/tensorflow_datasets/translate/wmt.py", line 625, in __init__
    raise ValueError(
ValueError: Failed to construct dataset wmt_translateThe raw `wmt_translate` can only be instantiated with the config kwargs. You may want to use one of the `wmtYY_translate` implementation instead to get the WMT dataset for a specific year.
```

**Expected behavior**
The script is successful.

**Comment by Conchylicultor** [comment]
This is intended. As the error message say:
```
ValueError: The raw `wmt_translate` can only be instantiated with the config kwargs.
You may want to use one of the `wmtYY_translate` implementation instead to get the WMT
dataset for a specific year.
```

You likely want to use wmt18, wmt17,... instead, or manually create a `tfds.translate.WmtConfig()`.
