### ISSUE TITLE
WMT14 de-en "AssertionError: Sizes do not match"

### ISSUE THREAD

**Issue by jiunoh** [tensorflow/datasets#2474]
**Short description**
`tfds.load(data_dir='./tensorflow_datasets', name='wmt14_translate/de-en', with_info=True, as_supervised=True)`
this gets
```
**AssertionError: Sizes do not match: 201854 vs 202002** for ../tensorflow_datasets/downloads/extracted/TAR_GZ.statmt.org_wmt14_training-parallel-nc-v9Kk5PK6ZZROqhtS0FWYopB3pKxYzPXQowHgBUqV7eV3U.tgz/training/news-commentary-v9.de-en.de vs ../tensorflow_datasets/downloads/extracted/TAR_GZ.statmt.org_wmt14_training-parallel-nc-v9Kk5PK6ZZROqhtS0FWYopB3pKxYzPXQowHgBUqV7eV3U.tgz/training/news-commentary-v9.de-en.en.
```
again and again.

**Environment information**
* Operating System: <Ubuntu 18.04>
* Python version: <3.6.9>
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly, also tried tensorflow-datasets==3.2.1
* `tensorflow`/`tf-nightly` version: tf-nightly, also tried tensorflow-gpu==2.3.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? yes

**Reproduction instructions**

```
`tfds.load(data_dir='./tensorflow_datasets', name='wmt14_translate/de-en', with_info=True, as_supervised=True)`
```

**Link to logs**

**Expected behavior**
I want the WMT2014 de-en dataset.

**Additional context**
The error always occurs for news-commentary. Also, I got 'All attempts to get a Google authentication bearer token failed' message.
full log:

```
2020-09-22 06:32:16.080181: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
in main function
2020-09-22 06:32:18.712241: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'".
Downloading and preparing dataset wmt14_translate/de-en/1.0.0 (download: 1.58 GiB, generated: Unknown size, total: 1.58 GiB) to ../tensorflow_datasets/wmt14_translate/de-en/1.0.0...
Dl Completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 4/4 [2:19:36<00:00, 1695.62s/ url]
Extraction completed...: 100%|█████████████████████████████████████████████████████████████████████████████████| 4/4 [2:19:36<00:00, 2094.18s/ file]
Extraction completed...: 100%|█████████████████████████████████████████████████████████████████████████████████| 4/4 [2:19:36<00:00, 1700.20s/ file]
Dl Size...: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 1614/1614 [2:19:36<00:00,  5.19s/ MiB]

Dl Completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 4/4 [2:19:36<00:00, 2094.18s/ url]
Extraction completed...: 0 file [00:00, ? file/s]
Extraction completed...: 0 file [00:00, ? file/s]
Traceback (most recent call last):          
  File "load_test.py", line 514, in <module>
    examples, metadata = tfds.load(data_dir='../tensorflow_datasets', name='wmt14_translate/de-en', with_info=True, as_supervised=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/registered.py", line 371, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 376, in download_and_prepare
    download_config=download_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1019, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 951, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1034, in _prepare_split
    total=split_info.num_examples, leave=False):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/translate/wmt.py", line 782, in _generate_examples
    for sub_key, ex in sub_generator(*files):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/translate/wmt.py", line 844, in _parse_parallel_sentences
    len(l1_sentences), len(l2_sentences), f1_i, f2_i))
AssertionError: Sizes do not match: 201854 vs 202002 for ../tensorflow_datasets/downloads/extracted/TAR_GZ.statmt.org_wmt14_training-parallel-nc-v9Kk5PK6ZZROqhtS0FWYopB3pKxYzPXQowHgBUqV7eV3U.tgz/training/news-commentary-v9.de-en.de vs ../tensorflow_datasets/downloads/extracted/TAR_GZ.statmt.org_wmt14_training-parallel-nc-v9Kk5PK6ZZROqhtS0FWYopB3pKxYzPXQowHgBUqV7eV3U.tgz/training/news-commentary-v9.de-en.en.
```

-----------------------------------------------------------------------
edited:
I installed tensorflow-gpu==2.1.0, tfds==1.3.2 (which I used before) and used this command
` python -m tensorflow_datasets.scripts.download_and_prepare --register_checksums=True --datasets='wmt14_translate/de-en'
`
added --register_checksums because the 0.0.3 version got wrong checksum error.
This command successfully downloaded the 0.0.3 version.

**Comment by rohit11544** [comment]
Is this issue closed?

**Comment by vijayphoenix** [comment]
FIxed by https://github.com/tensorflow/datasets/pull/2633
