### ISSUE TITLE
Bug dataset UCF-101 download

### ISSUE THREAD

**Issue by guillaumelorre28** [tensorflow/datasets#2498]
**Short description**
An error occurs at the beginning of the download of UCF-101 dataset.

**Environment information**
* Operating System: Ubuntu
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: 3.2.1
* `tensorflow`/`tf-nightly` version: 2.3.0

**Reproduction instructions**

```python
import tensorflow_datasets as tfds

# Construct a tf.data.Dataset
ds = tfds.load('ucf101/ucf101_1_256', split='train', shuffle_files=True, data_dir='/data/tensorflow_datasets')

```

**Link to logs**

```
Traceback (most recent call last):
  File "data/tf_datasets_ucf_101.py", line 9, in <module>
    ds = tfds.load('ucf101/ucf101_1_256', split='train', shuffle_files=True, data_dir='/data/tensorflow_datasets')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/registered.py", line 371, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 376, in download_and_prepare
    download_config=download_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1019, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 939, in _download_and_prepare
    dl_manager, **split_generators_kwargs):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/video/ucf101.py", line 163, in _split_generators
    downloaded_urls = dl_manager.download_and_extract(urls_to_download)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/download_manager.py", line 604, in download_and_extract
    return _map_promise(self._download_extract, url_or_urls)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/download_manager.py", line 641, in _map_promise
    res = tf.nest.map_structure(_wait_on_promise, all_promises)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py", line 635, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/download_manager.py", line 635, in _wait_on_promise
    return p.get()
  File "/usr/local/lib/python3.6/dist-packages/promise/promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "/usr/local/lib/python3.6/dist-packages/promise/promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/usr/local/lib/python3.6/dist-packages/promise/promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/downloader.py", line 145, in _sync_download
    with _open_url(url) as (response, iter_content):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/downloader.py", line 191, in _open_with_requests
    with session.get(url, stream=True) as response:
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.crcv.ucf.edu', port=443): Max retries exceeded with url: /data/UCF101/UCF101TrainTestSplits-RecognitionTask.zip (Caused by SSLError(SSLError(1,
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))


```

**Expected behavior**

No error when downloading the dataset

**Comment by Acebee** [comment]
you can solve the issue by modifying the downloader.py(envs\py36\Lib\site-packages\tensorflow_datasets\core\download\extractor.py) file at line 191:
`with session.get(url, stream=True) as response: `
to
`with session.get(url, stream=True,verify=False) as response:`

**Comment by Conchylicultor** [comment]
Did this worked ? If so, you can send a PR to add a `tfds.download.DownloadConfig(verify_ssl=False)` to disable certificat checking.

**Comment by Conchylicultor** [comment]
There is now a `tfds.download.DownloadConfig(verify_ssl=False)` in `tfds-nightly`. Please use this to silent the error.

**Comment by aiporre** [comment]
FYI, to used with the tfds.load function:

 ```
config = tfds.download.DownloadConfig(verify_ssl=False)
ds = tfds.load(name, split=split_name, shuffle_files=True, data_dir=dataset_dir, download_and_prepare_kwargs={"download_config" : config})
```

**Comment by innat** [comment]
Alternate solution

```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
