### ISSUE TITLE
tfds-nightly installs wrong avro-python3 and dill

### ISSUE THREAD

**Issue by chrisrytting** [tensorflow/datasets#2636]
**Short description**
When I create a new python virtual environment, so that there are zero python packages installed, I run `pip install 'tfds-nightly[c4]'`, and I am informed that the versions of avro-python3 and dill are incompatible with apache-beam 2.24.0. Is this an apache problem or a tfds problem?

**Environment information**
* Operating System: Ubuntu 18.04
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly==4.0.1.dev202010220107
* `tensorflow`/`tf-nightly` version: tensorflow==2.3.1

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
Yes, just barely installed.

**Reproduction instructions**
From commandline, 
`source env/bin/activate` (where env is a brand new python virtual env)
`pip install 'tfds-nightly[c4]'`

yields 

```
...
apache-beam 2.24.0 requires avro-python3!=1.9.2,<1.10.0,>=1.8.1; python_version >= "3.0", but you'll have avro-python3 file-.avro-VERSION.txt which is incompatible.
apache-beam 2.24.0 requires dill<0.3.2,>=0.3.1.1, but you'll have dill 0.3.2 which is incompatible.
...
```

**Expected behavior**
Expected this clean pip install not to install incompatible dependency versions

**Comment by Conchylicultor** [comment]
It is likely an error you can ignore. But you can force pip install dill 0.3.1.1 if you prefer

**Comment by chrisrytting** [comment]
Are you sure? Because when I tried to run an apache beam job on google cloud dataflow with 

```
python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=c4/en \
  --data_dir=gs://$MY_BUCKET/tensorflow_datasets \
  --beam_pipeline_options="project=$MY_PROJECT,job_name=c4,staging_location=gs://$MY_BUCKET/binaries,temp_location=gs://$MY_BUCKET/temp,runner=DataflowRunner,requirements_file=/tmp/beam_requirements.txt,experiments=shuffle_mode=service,region=$MY_REGION,max_num_workers=448,worker_machine_type=e2-standard-32"
```

Like 3 hours into the job I get the following error and it makes my multiple hundreds of dollars job fail:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/dataflow_worker/batchworker.py", line 649, in do_work
work_executor.execute()
File "/usr/local/lib/python3.6/site-packages/dataflow_worker/executor.py", line 179, in execute
op.start()
File "dataflow_worker/shuffle_operations.py", line 63, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
File "dataflow_worker/shuffle_operations.py", line 64, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
File "dataflow_worker/shuffle_operations.py", line 79, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
File "dataflow_worker/shuffle_operations.py", line 80, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
File "dataflow_worker/shuffle_operations.py", line 84, in dataflow_worker.shuffle_operations.GroupedShuffleReadOperation.start
File "apache_beam/runners/worker/operations.py", line 332, in apache_beam.runners.worker.operations.Operation.output
File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
File "dataflow_worker/shuffle_operations.py", line 261, in dataflow_worker.shuffle_operations.BatchGroupAlsoByWindowsOperation.process
File "dataflow_worker/shuffle_operations.py", line 268, in dataflow_worker.shuffle_operations.BatchGroupAlsoByWindowsOperation.process
File "apache_beam/runners/worker/operations.py", line 332, in apache_beam.runners.worker.operations.Operation.output
File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
File "apache_beam/runners/common.py", line 1215, in apache_beam.runners.common.DoFnRunner.process
File "apache_beam/runners/common.py", line 1279, in apache_beam.runners.common.DoFnRunner._reraise_augmented
File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
File "apache_beam/runners/common.py", line 569, in apache_beam.runners.common.SimpleInvoker.invoke_process
File "apache_beam/runners/common.py", line 1371, in apache_beam.runners.common._OutputProcessor.process_outputs
File "apache_beam/runners/worker/operations.py", line 195, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
File "apache_beam/runners/worker/operations.py", line 670, in apache_beam.runners.worker.operations.DoOperation.process
File "apache_beam/runners/worker/operations.py", line 671, in apache_beam.runners.worker.operations.DoOperation.process
File "apache_beam/runners/common.py", line 1215, in apache_beam.runners.common.DoFnRunner.process
File "apache_beam/runners/common.py", line 1294, in apache_beam.runners.common.DoFnRunner._reraise_augmented
File "/usr/local/lib/python3.6/site-packages/future/utils/_init_.py", line 446, in raise_with_traceback
raise exc.with_traceback(traceback)
File "apache_beam/runners/common.py", line 1213, in apache_beam.runners.common.DoFnRunner.process
File "apache_beam/runners/common.py", line 570, in apache_beam.runners.common.SimpleInvoker.invoke_process
File "/mnt/pccfs/backed_up/crytting/persuasion/createc4/lib/python3.6/site-packages/apache_beam/transforms/core.py", line 815, in <lambda>
self.process = lambda element: fn(element)
TypeError: clean_page() got an unexpected keyword argument 'badwords_regex' [while running 'clean_pages']
```

and the only thing I can think of is that I have a bad dependency version somewhere or something. Any ideas?

**Comment by Conchylicultor** [comment]
@adarob FYI

**Comment by adarob** [comment]
@chrisrytting your issue should have been fixed -- sorry I forgot to update the bug
It seems like the original issue is the same as #2491

**Comment by vijayphoenix** [comment]
This seems to be the solution https://github.com/tensorflow/datasets/issues/2491#issuecomment-722562290
