### ISSUE TITLE
tfds is not running on Apple Silicon M1

### ISSUE THREAD

**Issue by mabidou** [tensorflow/datasets#2872]
I managed to install without any issue & here is what I get on listing it

```
(tfenv) mgd@MGD-m1 ~ % conda list tensorflow
# packages in environment at /Users/mgd/opt/anaconda3/envs/tfenv:
#
# Name                    Version                   Build  Channel
tensorflow-datasets       4.1.0                    pypi_0    pypi
tensorflow-metadata       0.26.0                   pypi_0    pypi
(tfenv) mgd@MGD-m1 ~ % 
```

On running it even from terminal, I got the following error

```
(tfenv) mgd@MGD-m1 ~ % python
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_datasets as tfds


Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install TensorFlow Datasets. This is so that users can decide whether to install the GPU-enabled TensorFlow package. To use TensorFlow Datasets, please install the most recent version of TensorFlow, by following instructions at https://tensorflow.org/install.


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mgd/opt/anaconda3/envs/tfenv/lib/python3.8/site-packages/tensorflow_datasets/__init__.py", line 51, in <module>
    from tensorflow_datasets import __init__py3 as api
  File "/Users/mgd/opt/anaconda3/envs/tfenv/lib/python3.8/site-packages/tensorflow_datasets/__init__py3.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/Users/mgd/opt/anaconda3/envs/tfenv/lib/python3.8/site-packages/tensorflow_datasets/core/__init__.py", line 21, in <module>
    tf_compat.ensure_tf_install()
  File "/Users/mgd/opt/anaconda3/envs/tfenv/lib/python3.8/site-packages/tensorflow_datasets/core/tf_compat.py", line 44, in ensure_tf_install
    import tensorflow.compat.v2 as tf  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'tensorflow'
>>> 
```

**TensorFlow** has the same issue and I have reported it in https://github.com/tensorflow/tensorflow/issues/45645 

**Environment information**

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.0.1
* tfds version: 4.1.0
* Python version: 3.8.5
* Installed using: pip

**Comment by Conchylicultor** [comment]
As the log says:
```
Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install
TensorFlow Datasets. This is so that users can decide whether to install the GPU-enabled
TensorFlow package. To use TensorFlow Datasets, please install the most recent version of
TensorFlow, by following instructions at https://tensorflow.org/install.
```
