### ISSUE TITLE
raise source.error("unbalanced parenthesis") re.error: unbalanced parenthesis at position 27

### ISSUE THREAD

**Issue by TheLostProgrammer** [tensorflow/datasets#2940]
Hi, I have started using pytube yesterday with tkinter and I had everything working perfectly. I then uninstalled pytube to install pytube3 but then errors began to take place. I then uninstalled pytube3 and reinstalled pytube but I keep getting a range of errors. My current error is: 
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1884, in __call__
    return self.func(*args)
  File "/Users/thelostprogrammer/PycharmProjects/converter/main.py", line 37, in download
    YouTube(url.get()).streams.filter(res=resolution.get()).first().download(location.get(), filename="video_file8757")
  File "/Users/thelostprogrammer/PycharmProjects/converter/venv/lib/python3.9/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/Users/thelostprogrammer/PycharmProjects/converter/venv/lib/python3.9/site-packages/pytube/__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)`

Here is my code, it is long and might be stupid but I am just beginning with these modules:
```
from tkinter import *
from pytube import YouTube
import pafy
import glob
import os

window = Tk()
window.geometry("400x350")
window.title("Youtube Video Downloader")
url_input = StringVar()
url = StringVar()
url_input.set("Enter the Youtube Video URL")
Label(window, textvariable=url_input).pack()
Entry(window, textvariable=url, width=30).pack(pady=10)

location_input = StringVar()
location = StringVar()
location_input.set("Enter download location")
Label(window, textvariable=location_input).pack()
Entry(window, textvariable=location, width=30).pack(pady=10)

resolution_input = StringVar()
resolution = StringVar()
resolution_input.set("Enter desired resolution (Make sure video supports it)\n1080p recommended")
Label(window, textvariable=resolution_input).pack()
Entry(window, textvariable=resolution, width=30).pack(pady=10)


def download():
    try:
        result = pafy.new(url.get())
        result1 = result.title.replace(" ", "_")
        result2 = result.title.replace("_", " ")
        url_input.set("Downloading...")
        location_input.set("Getting file location...")
        resolution_input.set("Getting desired resolution...")
        window.update()
        YouTube(url.get()).streams.filter(res=resolution.get()).first().download(location.get(), filename="video_file8757")
        YouTube(url.get()).streams.filter(only_audio=True).first().download(location.get(), filename="audio_file7574")
        os.system("ffmpeg -i {0}/video_file8757.mp4 -i {0}/audio_file7574.mp4 -c:v copy -c:a aac {0}/{1}.mp4".format(location.get(), result1))
        for i in glob.glob("{}/video_file8757.mp4".format(location.get())):
            os.remove(i)
        for i in glob.glob("{}/audio_file7574.mp4".format(location.get())):
            os.remove(i)
        os.rename(fr'{location.get()}/{result1 + ".mp4"}',
                  fr'{location.get()}/{result2 + ".mp4"}')
        url_input.set("Video Downloaded Successfully")
        location_input.set("Check your download location to find file")
        resolution_input.set(f"Video is {resolution.get()}")

    except Exception as e:
        url_input.set("Error: " + str(e))
        window.update()


Button(window, text="Download", command=download).pack()

window.mainloop()
```
**Does anyone know how I can fix this irritating problem?**

* Operating System: macOS 11.1
* Python version: 3.9.1

**Comment by Conchylicultor** [comment]
Closing as it seems unrelated to TFDS
