### ISSUE TITLE
dl_manager not downloading and/or extracting files as expected

### ISSUE THREAD

**Issue by NikhilBartwal** [tensorflow/datasets#3054]
**Short description**
While working on an issue, when i tried running `dl_manager` on my local environment to better understand how it works, but it st doesn't download the file. The file in question was hosted as a public kaggle dataset

**Environment information**
* Operating System: <os> Windows 10
* Python version: 3.8.6
* `tensorflow-datasets`/`tfds-nightly` version: 2.4.0
* `tensorflow`/`tf-nightly` version: Latest source build

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Y

**Reproduction instructions**

```
dl_manager = tfds.download.DownloadManager(download_dir='F:/mydata') #any local path
downloaded_dir = dl_manager.download('https://www.kaggle.com/nikhilbartwal001/celeba/download')
```

**Link to logs**
```
>>> dl_manager = tfds.download.DownloadManager(download_dir='F:/celeba')
>>> paths = dl_manager.download('https://www.kaggle.com/nikhilbartwal001/celeba/download')
Dl Size...: 0 MiB [00:00, ? MiB/s]█████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.27 url/s]
Dl Completed...: 100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.26 url/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 549, in download
    return _map_promise(self._download, url_or_urls)
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 778, in _map_promise
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "F:\python\lib\site-packages\tensorflow\python\util\nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "F:\python\lib\site-packages\tensorflow\python\util\nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 778, in <lambda>
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "F:\python\lib\site-packages\promise\promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "F:\python\lib\site-packages\promise\promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "F:\python\lib\site-packages\promise\promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "F:\python\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "F:\python\lib\site-packages\promise\promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 360, in <lambda>
    return future.then(lambda dl_result: self._register_or_validate_checksums(  # pylint: disable=g-long-lambda
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 424, in _register_or_validate_checksums
    return self._rename_and_get_final_dl_path(
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 448, in _rename_and_get_final_dl_path
    if path.is_relative_to(self._manual_dir):  # Manually downloaded data
  File "f:\tfds\datasets\tensorflow_datasets\core\utils\type_utils.py", line 103, in is_relative_to
    self.relative_to(*other)
  File "F:\python\lib\pathlib.py", line 898, in relative_to
    to_drv, to_root, to_parts = self._parse_args(other)
  File "F:\python\lib\pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Expected behavior**
The data should have been downloaded and its location stored in `downloaded_dir`.

**Additional context**
If the problem persists due to this being a Kaggle download link, it would be great to know how else would it be feasible to use a Kaggle dataset in TFDS. Thank you!

**Comment by NikhilBartwal** [comment]
@Conchylicultor I was working on #2406 as the `celeb_a` dataset is still broken and the download links need to be updated. I have created a custom public dataset on Kaggle in accordance with the dataset generation script but `dl_manager` does not seem to be downloading the file. It would be great if you could help me clear this out. Thank you!

**Comment by Conchylicultor** [comment]
Thank you for reporting. Sending a fix now

**Comment by vijayphoenix** [comment]
@NikhilBartwal Downloading any Kaggle datasets requires login.

So, you can use this API https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager#download_kaggle_data

**Comment by Conchylicultor** [comment]
However, we are only using the original dataset author URL. We cannot use data re-hosted by third party users.

**Comment by NikhilBartwal** [comment]
@Conchylicultor I can understand. However there is also an official CelebA Kaggle dataset uploaded by the Kaggle Team itself [here](https://www.kaggle.com/jessicali9530/celeba-dataset?select=list_eval_partition.csv). Do you think we can use this one?

**Comment by NikhilBartwal** [comment]
Thank you for the help @vijayphoenix. However the same error happens when we use the example provided in the TFDS documentation [here](https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager#example_of_usage) as well. It would be great if you could clarify that. Thanks!

**Comment by vijayphoenix** [comment]
All the URLs in that example are fake. (They are used just as a placeholder)
Please try again with some working URLs

**Comment by NikhilBartwal** [comment]
Hey @vijayphoenix, I just tried doing that with the same URL that titanic dataset uses in the TFDS script (i.e. [this](https://www.openml.org/data/get_csv/16826755/phpMYEkMl)) but the same error happened again. 
However, the file was downloaded successfully but the error persisted. Also, the file location was not stored in the variable as it shuold have been.
Here are the logs:
```
>>> dl_manager = tfds.download.DownloadManager(download_dir='F:/mydata')
>>> paths = dl_manager.download('https://www.openml.org/data/get_csv/16826755/phpMYEkMl')
Dl Size...: 0 MiB [00:00, ? MiB/s]█████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.23 url/s]
Dl Completed...: 100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.22 url/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 549, in download
    return _map_promise(self._download, url_or_urls)
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 778, in _map_promise
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "F:\python\lib\site-packages\tensorflow\python\util\nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "F:\python\lib\site-packages\tensorflow\python\util\nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 778, in <lambda>
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "F:\python\lib\site-packages\promise\promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "F:\python\lib\site-packages\promise\promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "F:\python\lib\site-packages\promise\promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "F:\python\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "F:\python\lib\site-packages\promise\promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 360, in <lambda>
    return future.then(lambda dl_result: self._register_or_validate_checksums(  # pylint: disable=g-long-lambda
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 424, in _register_or_validate_checksums
    return self._rename_and_get_final_dl_path(
  File "f:\tfds\datasets\tensorflow_datasets\core\download\download_manager.py", line 448, in _rename_and_get_final_dl_path
    if path.is_relative_to(self._manual_dir):  # Manually downloaded data
  File "f:\tfds\datasets\tensorflow_datasets\core\utils\type_utils.py", line 103, in is_relative_to
    self.relative_to(*other)
  File "F:\python\lib\pathlib.py", line 898, in relative_to
    to_drv, to_root, to_parts = self._parse_args(other)
  File "F:\python\lib\pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by vijayphoenix** [comment]
Seems like Conchylicultor has already fixed this issue by PR https://github.com/tensorflow/datasets/pull/3055 :smile:

**Comment by vijayphoenix** [comment]
Fixed by https://github.com/tensorflow/datasets/pull/3055
