### ISSUE TITLE
Support for mirroring datasets for use without an internet connection

### ISSUE THREAD

**Issue by orf** [tensorflow/datasets#3125]
**Is your feature request related to a problem? Please describe.**

For compliance and security reasons training and experimentation may be done in environments without access to the internet. While datasets provides a local cache it's not clear or documented how you would utilize an internal mirror or proxy for many distributed clients.

An internal mirror also helps prevent against transient network issues, improves performance and reduces network load on external services when using stateless machines that will have an empty cache on startup.

**Describe the solution you'd like**

I'd like to be able to export an environment variable like `TFDS_MIRROR=s3://some-bucket/some-prefix/` and have tfds use that to fetch all files and make no network requests. A separate process can populate the mirror. A simple key structure including the `sha256` hash of the URL mapping to the data would be sufficient:

```python
def download(url):
    mirror_prefix = os.environ['TFDS_MIRROR']
    url_hash = sha256(url)
    try:
        return download_from(f'{mirror_prefix}/{url_hash}')
    except NotFound:
        print(f'URL {url} not reachable')
```

**Describe alternatives you've considered**

You could mount a shared distributed filesystem on `$TFDS_CACHE_DIR`, but tfds will still try and make network requests. Other machines might write to this location during runtime and the performance would not be optimal.

**Comment by Conchylicultor** [comment]
Would https://www.tensorflow.org/datasets/overview#manual_download_if_download_fails works for you ?
Also it the dataset is already generated. You don't need internet anymore

**Comment by preeti13456** [comment]
Do you want all the data to be synchronous at the same time or it's a different change you were asking for?

**Comment by orf** [comment]
Thanks for the replies. Manual download if download fails requires the download to fail. On some environments this may take a long time, especially with retries. It also requires a _local_ cache running on some form of filesystem abstraction. After glancing at the code it seems like it makes direct use of `pathlib` and so can't use some of the tensorflow abstractions around this (so setting `manual_dir` to `s3://bucket/cache/` won't work).

I'm not sure what you mean about synchronous, I'm just asking for the ability to try to pull all data from a specified mirror, _not_ a local filesystem or the remote source.

**Comment by Conchylicultor** [comment]
> Manual download if download fails requires the download to fail. On some environments this may take a long time, especially with retries.

This is not true. TFDS first look at manual dir, and only try to download if the download data isn't found

> After glancing at the code it seems like it makes direct use of pathlib and so can't use some of the tensorflow abstractions around this (so setting manual_dir to s3://bucket/cache/ won't work).

Also not true. TFDS uses a custom pathlib abstraction which support GCS, s3

**Comment by orf** [comment]
Ok, so that's really good to know. Thank you! I might suggest documenting this (unless it already is, and I'm blind?). I'll give this a try and report back if there are any issues I encounter.

Thanks again!

**Comment by orf** [comment]
Has this been tested with an object store like S3?

```
tmp.3UuZnUpF ❯ tfds build coil100 --download_dir=s3://tfds-onfido-test/download/
INFO[build.py]: Loading dataset coil100 from imports: tensorflow_datasets.image.coil100
2021-03-25 15:25:28.922641: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'".
INFO[dataset_info.py]: Load pre-computed DatasetInfo (eg: splits, num examples,...) from GCS: coil100/2.0.0
INFO[dataset_info.py]: Load dataset info from /var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmpvdpp4k34tfds
INFO[dataset_info.py]: Field info.module_name from disk and from code do not match. Keeping the one from code.
INFO[build.py]: download_and_prepare for dataset coil100/2.0.0...
INFO[dataset_builder.py]: Generating dataset coil100 (/Users/tom/tensorflow_datasets/coil100/2.0.0)
Downloading and preparing dataset 124.63 MiB (download: 124.63 MiB, generated: 124.74 MiB, total: 249.37 MiB) to /Users/tom/tensorflow_datasets/coil100/2.0.0...
Traceback (most recent call last):
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/bin/tfds", line 8, in <module>
    sys.exit(launch_cli())
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/main.py", line 120, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/main.py", line 115, in main
    args.subparser_fn(args)
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/build.py", line 199, in _build_datasets
    _download_and_prepare(args, builder)
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/build.py", line 355, in _download_and_prepare
    builder.download_and_prepare(
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 418, in download_and_prepare
    dl_manager = self._make_download_manager(
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 852, in _make_download_manager
    return download.DownloadManager(
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/core/download/download_manager.py", line 217, in __init__
    self._download_dir.mkdir(parents=True, exist_ok=True)
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow_datasets/core/utils/gpath.py", line 132, in mkdir
    tf.io.gfile.makedirs(self._path_str)
  File "/var/folders/k3/splrymbj4wn9fgzcfgkzy93h0000gn/T/tmp.3UuZnUpF/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 483, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unknown: : No response body.
```

Here I'm trying to build a single dataset and set the `download_dir` to a S3 bucket. Future invocations of `tfds` would be configured to use that prefix as a download directory and would then not require network access?
