### ISSUE TITLE
'glue/sst2': tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://firebasestorage.googleapis.com/ HTTP code: 403

### ISSUE THREAD

**Issue by tarrade** [tensorflow/datasets#3163]
**Short description**
cannot download sst2 tensorflow dataset: 
tensorflow_datasets.load(name='glue/sst2', data_dir='tensorflow-dataset', with_info=True)

**Environment information**
* Operating System: MacOS and Linux
* Python version: 3.6
* `tensorflow-datasets`/`tfds-nightly` version: 4.2.0
* `tensorflow`/`tf-nightly` version: 2.4.1

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
didn't try, was working before with various version of TF

**Reproduction instructions**

```
data, info = tensorflow_datasets.load(name='glue/sst2', data_dir='tensorflow-dataset', with_info=True)
```

**Link to logs**
>>> data, info = tensorflow_datasets.load(name='glue/sst2', data_dir='tensorflow-dataset', with_info=True)
Downloading and preparing dataset 7.09 MiB (download: 7.09 MiB, generated: Unknown size, total: 7.09 MiB) to tensorflow-dataset/glue/sst2/1.0.0...
Extraction completed...: 0 file [00:00, ? file/s]                                                                                                                                                 | 0/1 [00:00<?, ? url/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]
Dl Completed...:   0%|                                                                                                                                                                            | 0/1 [00:00<?, ? url/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/load.py", line 328, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py", line 446, in download_and_prepare
    download_config=download_config,
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1148, in _download_and_prepare
    dl_manager, **optional_pipeline_kwargs
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/text/glue.py", line 448, in _split_generators
    dl_dir = dl_manager.download_and_extract(self.builder_config.data_url)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 637, in download_and_extract
    return _map_promise(self._download_extract, url_or_urls)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 777, in _map_promise
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 777, in <lambda>
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/promise/promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/promise/promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/promise/promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/download/downloader.py", line 206, in _sync_download
    with _open_url(url, verify=verify) as (response, iter_content):
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/download/downloader.py", line 268, in _open_with_requests
    _assert_status(response)
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.6/site-packages/tensorflow_datasets/core/download/downloader.py", line 300, in _assert_status
    response.url, response.status_code))
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8. HTTP code: 403.
>>>

**Expected behavior**
download 'glue/sst2' without any issue, works fine for 'imdb_reviews
data, info = tensorflow_datasets.load(name='imdb_reviews', data_dir='tensorflow-dataset', as_supervised=True, with_info=True)
**Additional context**
was working in Dec 2020 at least

**Comment by NikhilBartwal** [comment]
@tarrade The issue seems to have been solved in `tfds-nightly` (This might be due to a faulty download URL in the earlier tfds)
You can install it by using `pip install tfds-nightly`. THe dataset is successfully being generated in the nightly update.

Please let us know if the issue persists!

**Comment by tarrade** [comment]
@NikhilBartwal thanks and I confirm that the issue is fixed in the nightly. I hope this fix will be collected soon in a new release > 4.2.0. Closing.
