### ISSUE TITLE
`huggingface:xnli` not generated due to `tuple` as key

### ISSUE THREAD

**Issue by NikhilBartwal** [tensorflow/datasets#3170]
**Short description**
The `huggingface:xnli` dataset is not generated as it contains a tuple as key (which should be str/int)

**Environment information**
* Operating System: Windows 10
* Python version: 3.8.0
* `tensorflow-datasets`/`tfds-nightly` version:4.2.0+nightly
* `tensorflow`/`tf-nightly` version: .2.4.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes

**Reproduction instructions**

```
>>> nik = tfds.load('huggingface:xnli')
Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to C:\Users\nikhil\tensorflow_datasets\xnli\ar\1.1.0...
Extraction completed...: 0 file [00:00, ? file/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]
Dl Completed...: 0 url [00:00, ? url/s] ? file/s]
Generating splits...:   0%|                                   Traceback (most recent call last):3 [00:00<?, ? splits/s]
  File "<stdin>", line 1, in <module>
  File "f:\tfds\datasets\tensorflow_datasets\core\load.py", line 328, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "f:\tfds\datasets\tensorflow_datasets\core\dataset_builder.py", line 453, in download_and_prepare
    self._download_and_prepare(
  File "f:\tfds\datasets\tensorflow_datasets\core\community\huggingface_wrapper.py", line 139, in _download_and_prepare
    return super()._download_and_prepare(*args, **kwargs)
  File "f:\tfds\datasets\tensorflow_datasets\core\dataset_builder.py", line 1178, in _download_and_prepare
    split_info_futures = [
  File "f:\tfds\datasets\tensorflow_datasets\core\dataset_builder.py", line 1179, in <listcomp>
    split_builder.submit_split_generation(  # pylint: disable=g-complex-comprehension
  File "f:\tfds\datasets\tensorflow_datasets\core\split_builder.py", line 295, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "f:\tfds\datasets\tensorflow_datasets\core\split_builder.py", line 365, in _build_from_generator
    writer.write(key, example)
  File "f:\tfds\datasets\tensorflow_datasets\core\tfrecords_writer.py", line 269, in write
    self._shuffler.add(key, serialized_example)
  File "f:\tfds\datasets\tensorflow_datasets\core\shuffle.py", line 218, in add
    hkey = self._hasher.hash_key(key)
  File "f:\tfds\datasets\tensorflow_datasets\core\hashing.py", line 96, in hash_key
    md5.update(_to_bytes(key))
  File "f:\tfds\datasets\tensorflow_datasets\core\hashing.py", line 70, in _to_bytes
    raise TypeError(f'Invalid key type: {data!r} ({type(data)})')
TypeError: Invalid key type: (0, 0) (<class 'tuple'>)
```

**Expected behavior**
The dataset should have been generated properly or a better error message given.

**Additional context**
I have opened an issue at HF [here](https://github.com/huggingface/datasets/issues/2229) and will be sending a fix for correcting `xnli`'s script.
However, I think we should add a better error message for inconsistant keys for the upcoming community datasets.
@Conchylicultor @vijayphoenix What do you think?

**Comment by NikhilBartwal** [comment]
The issue was solved by [this](https://github.com/huggingface/datasets/pull/2233) PR.
However, when it comes to community datasets, TFDS uses the same cached dataset script even if there was a change/update to the original script. I will be closing this issue for now and opening an enhancement issue to fix this.
