### ISSUE TITLE
Issues loading saved model  - TypeError: __init__() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by GrayWasTaken** [tensorflow/datasets#3175]
I'm trying to load a saved model but I am failing thus far. The solution I keep seeing is to add **kwargs to my layer class constructor but that didn't work either.

Loading code:
```py
model = tf.keras.models.load_model('newest_model.h5', custom_objects={
    'PositionalEncoding': PositionalEncoding,
    'MultiHeadAttention':MultiHeadAttention,
    'CustomSchedule': CustomSchedule})
```

Possibly relevant code:
```py
class PositionalEncoding(tf.keras.layers.Layer):
    def __init__(self, position, d_model):
        super(PositionalEncoding, self).__init__()
        self.pos_encoding = self.positional_encoding(position, d_model)

    def get_angles(self, position, i, d_model):
        angles = 1 / tf.pow(10000, (2 * (i // 2)) / tf.cast(d_model, tf.float32))
        return position * angles

    def positional_encoding(self, position, d_model):
        angle_rads = self.get_angles(
            position=tf.range(position, dtype=tf.float32)[:, tf.newaxis],
            i=tf.range(d_model, dtype=tf.float32)[tf.newaxis, :],
            d_model=d_model)
        # apply sin to even index in the array
        sines = tf.math.sin(angle_rads[:, 0::2])
        # apply cos to odd index in the array
        cosines = tf.math.cos(angle_rads[:, 1::2])

        pos_encoding = tf.concat([sines, cosines], axis=-1)
        pos_encoding = pos_encoding[tf.newaxis, ...]
        return tf.cast(pos_encoding, tf.float32)

    def call(self, inputs):
        return inputs + self.pos_encoding[:, :tf.shape(inputs)[1], :]

    def get_config(self):
        config = super().get_config().copy()
        config.update({
            'vocab_size': VOCAB_SIZE,
            'num_layers': NUM_LAYERS,
            'units': UNITS,
            'd_model': D_MODEL,
            'num_heads': NUM_HEADS,
            'dropout': DROPOUT,
        })
        return config
```

Full stack trace:
```
Traceback (most recent call last):
  File "/home/.../.../Transformer version/test.py", line 499, in <module>
    model = tf.keras.models.load_model('newest_model.h5', custom_objects={
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/save.py", line 201, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/model_config.py", line 59, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/layers/serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 668, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 668, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1279, in reconstruct_from_config
    process_layer(layer_data)
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1261, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/layers/serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 668, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 668, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1279, in reconstruct_from_config
    process_layer(layer_data)
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1261, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/layers/serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 675, in deserialize_keras_object
    deserialized_obj = cls.from_config(cls_config)
  File "/home/.../.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 740, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'name'
```

**Comment by Conchylicultor** [comment]
Closing this as this seems unrelated to TFDS. Try to post in tensorflow/tensorflow/
