### ISSUE TITLE
FileNotFoundError: Could not find dataset generation script: webtextlike.py.

### ISSUE THREAD

**Issue by JeanKaddour** [tensorflow/datasets#4159]
**Short description**
I try to prepare the Webtextlike dataset from C4.

I follow the instructions from the [TFDS website](https://www.tensorflow.org/datasets/catalog/c4)

After moving OpenWebText.zip to the manual folder, I get the following error:

```
W0922 13:14:43.353461 140244170822656 download_and_prepare.py:45] ***`tfds build` should be used instead of `download_and_prepare`.***
Traceback (most recent call last):
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/download_and_prepare.py", line 57, in <module>
    app.run(main, flags_parser=_parse_flags)
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/download_and_prepare.py", line 53, in main
    main_cli.main(args)
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/main.py", line 97, in main
    args.subparser_fn(args)
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 201, in _build_datasets
    for builder in _make_builders(args, ds_to_build):
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 210, in _make_builders
    builder_cls, builder_kwargs = _get_builder_cls(
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 270, in _get_builder_cls
    path = _search_script_path(ds_to_build)
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 308, in _search_script_path
    return _validate_script_path(path / f'{path.name}.py')
  File "/home/jean/miniconda3/envs/diff/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 333, in _validate_script_path
    raise FileNotFoundError(
FileNotFoundError: Could not find dataset generation script: /home/jean/c4/c4/webtextlike/webtextlike.py.
```

**Environment information**
* Operating System: Arch Linux
* Python version: 3.9.12
* tf-nightly==2.11.0.dev20220921
* tfds-nightly==4.6.0.dev202209220046

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?

Yes

**Reproduction instructions**

```python

python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=c4/webtextlike \
  --data_dir=/home/jean/c4

```

Since download_and_prepare seems to be deprecated by now, I also tried the below which yields the same error

```
tfds build c4/webtextlike
```

**Comment by JeanKaddour** [comment]
OK, not sure why exactly, but a second attempt with `tfds build c4/webtextlike` worked
