### ISSUE TITLE
Data preparation for "wmt14_translate/de-en" is broken with 4.8.0

### ISSUE THREAD

**Issue by dgrangier** [tensorflow/datasets#4590]
**Short description**

The last release broke 4.8.0 the data preparation for "wmt14_translate/de-en".
The preparation script fails when reading newscommentary data.

AssertionError: Sizes do not match: 201855 vs 201996 for tensorflow_datasets/downloads/extracted/TAR_GZ.training-parallel-nc-v9.tgz/training/news-commentary-v9.de-en.de vs tensorflow_datasets/downloads/extracted/TAR_GZ.training-parallel-nc-v9.tgz/training/news-commentary-v9.de-en.en.

I checked my downloaded files have the correct checksums and the extracted files have the same number of lines:
  201288 news-commentary-v9.de-en.de
  201288 news-commentary-v9.de-en.en
  
The data preparation works fine if I downgrade to 4.7.0 .

**Environment information**

Issue happens with 4.8.0 not with 4.7.0

**Reproduction instructions**

bash script:
```
mkdir -p ~/tensorflow_datasets/downloads/manual/
cd ~/tensorflow_datasets/downloads/manual/
url_checksums="https://raw.githubusercontent.com/tensorflow/datasets/"
url_checksums=${url_checksums}"963c318e6e39468357a3bc22ecf5f6e678f8edcf/"
url_checksums=${url_checksums}"tensorflow_datasets/url_checksums/"
wget -nc -nv ${url_checksums}"wmt14_translate.txt"
awk '{print $1}' wmt14_translate.txt | xargs -n 1 wget -nc -nv
python3 -c "import tensorflow_datasets as tfds; tfds.load('wmt14_translate/de-en')"
```

**Link to logs**

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/core/logging/__init__.py", line 273, in decorator
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/core/load.py", line 598, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 600, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1399, in _download_and_prepare
    future = split_builder.submit_split_generation(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/core/split_builder.py", line 326, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/core/split_builder.py", line 389, in _build_from_generator
    for key, example in utils.tqdm(
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/translate/wmt.py", line 790, in _generate_examples
    for sub_key, ex in sub_generator(*files):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_datasets/translate/wmt.py", line 851, in _parse_parallel_sentences
    assert len(l1_sentences) == len(l2_sentences), (
AssertionError: Sizes do not match: 201855 vs 201996 for tensorflow_datasets/downloads/extracted/TAR_GZ.training-parallel-nc-v9.tgz/training/news-commentary-v9.de-en.de vs tensorflow_datasets/downloads/extracted/TAR_GZ.training-parallel-nc-v9.tgz/training/news-commentary-v9.de-en.en.

**Expected behavior**
Dataset is prepared.

**Comment by tomvdw** [comment]
Hi dgrangier,

Thanks for reporting this! I managed to reproduce the error and we'll look into this. I'll keep you posted.

**Comment by tomvdw** [comment]
I just submitted a [commit](https://github.com/tensorflow/datasets/commit/a798685fdffb0353ee265a033fc76dee4cbbedac) that fixes the problem for me. I don't understand yet why using epath.Path isn't working, but we'll make sure to test this before we change it again. Let me know if the problem has gone away. PS, it might take a day or two before this is in TFDS nightly.
