### ISSUE TITLE
No such file or directory: '.../tensorflow_datasets/core/valid_tags.txt'

### ISSUE THREAD

**Issue by zhiyun** [tensorflow/datasets#4605]
**Short description**
I installed tensorflow_datasets and tried to run `tfds new mydataset` and saw the following error
```
Traceback (most recent call last):
  File "/Users/zhiyunlu/miniforge3/envs/tfds/bin/tfds", line 8, in <module>
    sys.exit(launch_cli())
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/main.py", line 104, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/main.py", line 99, in main
    args.subparser_fn(args)
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/new.py", line 65, in _create_dataset_files
    create_dataset_files(
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/new.py", line 90, in create_dataset_files
    _create_dataset_tags(info)
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/new.py", line 172, in _create_dataset_tags
    dataset_metadata.valid_tags_with_comments())
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_metadata.py", line 69, in valid_tags_with_comments
    line for line in _get_valid_tags_text().split("\n")
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_metadata.py", line 58, in _get_valid_tags_text
    return path.read_text("utf-8")
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/etils/epath/abstract_path.py", line 144, in read_text
    with self.open('r', encoding=encoding) as f:
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/etils/epath/gpath.py", line 226, in open
    gfile = self._backend.open(self._path_str, mode)
  File "/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/etils/epath/backend.py", line 104, in open
    return open(path, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zhiyunlu/miniforge3/envs/tfds/lib/python3.8/site-packages/tensorflow_datasets/core/valid_tags.txt'
```

**Environment information**
* Operating System: MacOS M1 
* Python version: python3.8
* `tensorflow-datasets`/`tfds-nightly` version: `tensorflow-datasets` v4.8.0
* `tensorflow`/`tf-nightly` version: <package and version>

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
No. It does not exist with the latest `tfds-nightly` as of 2022/12/28.

**Reproduction instructions**

```
conda create -n tfds python=3.8
conda activate tfds
pip install tensorflow-datasets
pip install wrapt

tfds new xxx
```

If you share a colab, make sure to update the permissions to share it.

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
What you expected to happen.

**Additional context**

**Comment by tomvdw** [comment]
Hi Zhiyun,
Thanks for reporting this. I've released 4.8.1 to fix this issue. Let me know if you have any more problems.
