### ISSUE TITLE
downsampled_imagenet broken (important for reproducing research)

### ISSUE THREAD

**Issue by marikgoldstein** [tensorflow/datasets#4662]
**Short description**

Hi tfds!

When trying to download [downsampled_imagenet](https://www.tensorflow.org/datasets/catalog/downsampled_imagenet) (32x32), I get a 404 (stack trace at end of issue) . This is because the imagenet link stored by tfds (https://image-net.org/small/download.php) is broken. That's also the same link most people previously used, I believe due to designing experiments after Pixel Recurrent Neural Networks https://arxiv.org/pdf/1601.06759.pdf.

There *is* a different currently working link for 32x32 imagenet (https://image-net.org/download-images.php, if you log in, you can see a 32x32 option). However several researchers have expressed concern that this one is somehow "wrong"/different for generative modeling purposes from the one in pixel RNNs (i.e the one originally stored by tfds).

In more detail, an anon. ICLR reviewer (will try to find the link) and another active researcher in the field (will tag them once I get their permission) have mentioned that (1) imagenet's current link is "wrong" in that it is "too easy" to get good likelihoods on it (2) tfds' was right (but now it is broken) and (3) there is some torrent that researchers pass around for the original "correct" version (but I cannot find it and this is not an ideal solution). 

The link stored by tfds is likely to have broken sometime more recently than 9 months ago since another google repo shared code that uses tfds to get downsampled_imagenet (I left an issue there https://github.com/google-research/vdm/issues/8) and their datasets.py file was pushed then.

Also, If not mistaken, I believe none of these are the same as [imagenet_resized(https://www.tensorflow.org/datasets/catalog/imagenet_resized)

In conclusion, the purpose of this issue is two-fold:
- for tfds to consider what to do with the broken link, in light of the above considerations.
- for the image modeling community to have a discussion to clarify differences in these datasets. I understand if it makes sense to move this discussion elsewhere, but this also seems like the easiest place to get people's attention about it.

One possible solution is to confirm that someone's saved copy is identical to the one tfds used to download from the now broken link, and for other researchers to confirm it, and then re-post it as an "old_downsampled_imagenet".

Thanks,
Mark

**Environment information**
* Operating System: Ubuntu VERSION="18.04.6 LTS (Bionic Beaver)"
* Python version: 3.9.12
* `tensorflow-datasets`/`tfds-nightly` version: tfds '4.7.0' and  tfds '4.8.2+nightly'
* `tensorflow`/`tf-nightly` version: tf '2.10.0'

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?

Yes 

**Reproduction instructions**

```python
import tensorflow_datasets as tfds                                                                                                                                                               
ds = tfds.load('downsampled_imagenet', split='validation', as_supervised=True, batch_size=128)
```

**Link to logs**
stack trace at bottom of issue 

**Expected behavior**
I know this is *not* tfds' fault, but instead is 404 on imagenet's website combined with some not so careful data provenance on behalf of our research community. But, it's important for the research community to know more about the relationship between
- the downsampled imagenet that tfds used to download
- the one available now on imagenet 
- if it is wrong for tfds to download the one currently on imagenet, why?

```
2023-01-18 12:03:50.178320: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-18 12:03:51.793197: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /home/marik/tensorflow_datasets/downsampled_imagenet/32x32/2.0.0...
Dl Size...: 0 MiB [00:00, ? MiB/s]                                                                                                                                       | 0/2 [00:00<?, ? url/s]
Dl Completed...:   0%|                                                                                                                                                   | 0/2 [00:00<?, ? url/s]
Traceback (most recent call last):
  File "/home/marik/imnet2.py", line 2, in <module>
    ds = tfds.load('downsampled_imagenet', split='validation', as_supervised=True, batch_size=128)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/logging/__init__.py", line 250, in decorator
    return function(*args, **kwargs)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/load.py", line 575, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 523, in download_and_prepare
    self._download_and_prepare(
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1244, in _download_and_prepare
    split_generators = self._split_generators(  # pylint: disable=unexpected-keyword-arg
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/image/downsampled_imagenet.py", line 102, in _split_generators
    train_path, valid_path = dl_manager.download([
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/download/download_manager.py", line 552, in download
    return _map_promise(self._download, url_or_urls)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/download/download_manager.py", line 770, in _map_promise
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow/python/util/nest.py", line 917, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow/python/util/nest.py", line 917, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/download/download_manager.py", line 770, in <lambda>
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/promise/promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/promise/promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/promise/promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/download/downloader.py", line 217, in _sync_download
    with _open_url(url, verify=verify) as (response, iter_content):
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/download/downloader.py", line 279, in _open_with_requests
    _assert_status(response)
  File "/home/marik/anaconda2/envs/myenv/lib/python3.9/site-packages/tensorflow_datasets/core/download/downloader.py", line 306, in _assert_status
    raise DownloadError('Failed to get url {}. HTTP code: {}.'.format(
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://image-net.org/small/train_32x32.tar. HTTP code: 404.
```

**Comment by marikgoldstein** [comment]
I also reached out to the imagenet moderators to hear their input and will post any response here.

**Comment by marikgoldstein** [comment]
@Kim-Dongjun provided a good explanation and shared the location of the torrent that people use for the original data from pixel rnn. Here is Dongjun's explanation of the discrepancy (which also coincides with things I've heard from some authors at talks/conferences):

- There is a downsampled ImageNet dataset, which I call it "small".
- The small dataset was widely used in the community of generative models for long time
- but StyleGAN-XL, Efficient-VDVAE, or other large-scale papers tend to use ILSVRC12 dataset for their report on ImageNet 32x32 or ImageNet 64x64.
- The small dataset, however, is unattainable officially. It is available [at this torrent link](https://academictorrents.com/details/bf62f5051ef878b9c357e6221e879629a9b4b172)
- it is strange that we have to use "torrent" for the research, but as far as I know, there is no other websites that we can download the downsampled "small" ImageNet dataset.
- The signal is that the downsampled dataset has 49999 validation data, whereas the original ILSVRC12 dataset has 50000 validation data.
- The downsampled dataset is from Pixel RNN paper.

**Comment by marikgoldstein** [comment]
Here is a summary.

For imagenet 32x32, some papers use an "old" version and some use a "new" version.

- the "new" one is the one current available [here](https://image-net.org/download-images.php)
- the "old" one was previously available [here](https://image-net.org/small/download.php)
- the "old" one is still unofficially available [at this torrent link](https://academictorrents.com/details/bf62f5051ef878b9c357e6221e879629a9b4b172)
- TFDS has two imagenet 32x32's : "downsampled_imagenet" and "imagenet_resized"
- tfds "resized" is a different dataset unrelated to this discussion.
- tfds "downsampled" currently gives a 404 error because it goes to the "old" link
- unfortunately, it's not always clear in papers who used "old", "new". or "resized", and it affects likelihoods / ability to reproduce research

My proposals are
- tfds team should choose which dataset to point to by default to fix the 404 (perhaps the currently officially available "new" one from imagenet)
- the tfds team could consider whether it makes sense to somehow host the "old" one to help reproduce research. If so, which would be the ground truth source? the torrent? the original pixelrnn authors? 

Thanks, curious about others' take on this issue.
