### ISSUE TITLE
[bug] tfds plant_leaves downloads failing

### ISSUE THREAD

**Issue by jamesbraza** [tensorflow/datasets#4744]
**Short description**

I am getting timeouts when trying to download the [plant_leaves](https://www.tensorflow.org/datasets/catalog/plant_leaves) dataset on both December 4th 2022 and February 17th, 2023.

**Environment information**
* Operating System: macOS Monterey version 12.6
* Python version: 3.10
* `tensorflow-datasets`/`tfds-nightly` version: 4.8.2
* `tensorflow`/`tf-nightly` version: tensorflow-macos==2.11.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`)?  Sorry, didn't try this

**Reproduction instructions**

```python
import tensorflow_datasets as tfds

dataset = tfds.load(name="plant_leaves", split="train", as_supervised=True)
```

Gives:

```python
File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/download/downloader.py", line 306, in _assert_status
    raise DownloadError('Failed to get url {}. HTTP code: {}.'.format(
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://data.mendeley.com/v1/datasets/hb74ynkjcn/1/files/7f977a2c-aa75-4610-a6f6-84c8738d8c79/0001_0001.JPG. HTTP code: 404.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py", line 250, in decorator
    return function(*args, **kwargs)
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/load.py", line 575, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py", line 523, in download_and_prepare
    self._download_and_prepare(
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1244, in _download_and_prepare
    split_generators = self._split_generators(  # pylint: disable=unexpected-keyword-arg
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/image_classification/plant_leaves.py", line 123, in _split_generators
    raise DownloadRetryLimitReachedError(
tensorflow_datasets.image_classification.plant_leaves.DownloadRetryLimitReachedError: Retry limit reached. Try downloading the dataset again.
```

**Link to logs**

```none
Downloading and preparing dataset 6.81 GiB (download: 6.81 GiB, generated: Unknown size, total: 6.81 GiB) to /Users/james.braza/tensorflow_datasets/plant_leaves/0.1.0...
Dl Completed...: 0 url [00:00, ? url/s]
Dl Completed...:   0%|          | 0/1 [00:00<?, ? url/s]
Dl Completed...:   0%|          | 0/2 [00:00<?, ? url/s]
...
Dl Completed...:   0%|          | 0/2133 [00:00<?, ? url/s]
...
Dl Completed...:   0%|          | 0/4501 [00:01<?, ? url/s]
Dl Completed...:   0%|          | 0/4502 [00:01<?, ? url/s]
Dl Size...: 0 MiB [00:02, ? MiB/s]
Dl Completed...:   0%|          | 0/4502 [00:02<?, ? url/s]
Dl Completed...: 0 url [00:00, ? url/s]
Dl Completed...:   0%|          | 0/1 [00:00<?, ? url/s]
Dl Completed...:   0%|          | 0/2 [00:00<?, ? url/s]
...
```

**Expected behavior**

I expect the download to work.

**Additional context**

Coming from https://github.com/tensorflow/tensorflow/issues/58777 as requested by @gaikwadrahul8.

**Comment by yamanoko** [comment]
I am still working on it. I was aware that this is due to a change of images URL format in Mendeley. And I also confirmed there is a same issue in 'PlantaeK' datasets.
Anyway, I'll keep trying to solve this problem. I would appreciate if someone gives me a hand because it is my first opensource contribution.
Thanks!
