### ISSUE TITLE
Cosmos QA Key Error

### ISSUE THREAD

**Issue by conceptofmind** [tensorflow/datasets#4817]
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET
```
Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /home/henry/tensorflow_datasets/cosmos_qa/1.0.0...
Dl Size...: 100%|███████████████████████████████████████████████████████████| 18788794/18788794 [00:00<00:00, 6419510738.79 MiB/s]
Dl Completed...: 100%|███████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 959.58 url/s]
Traceback (most recent call last):                                                                                                
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/seqio/dataset_providers.py", line 496, in get_dataset
    return self.tfds_dataset.load(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/seqio/utils.py", line 180, in load
    return tfds.load(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/load.py", line 640, in load
    _download_and_prepare_builder(dbuilder, download, download_and_prepare_kwargs)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/load.py", line 499, in _download_and_prepare_builder
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 632, in download_and_prepare
    self._download_and_prepare(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1521, in _download_and_prepare
    future = split_builder.submit_split_generation(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/split_builder.py", line 341, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/split_builder.py", line 406, in _build_from_generator
    for key, example in utils.tqdm(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/question_answering/cosmos_qa.py", line 98, in _generate_examples
    yield row['id'], row
KeyError: 'id'
```

**Short description**
KeyError for Comos QA dataset: https://www.tensorflow.org/datasets/catalog/cosmos_qa

**Environment information**
* Operating System: Ubuntu 18
* Python version: Python 3.8+
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly-4.8.3.dev202303220045

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?

Yes

**Code from Flan Seqio**
```python
 @seqio.map_over_dataset
 def _process_cosmos_qa(example):
   """Process cosmos_qa dataset example."""
   label = tf.cast(example['label'], tf.int32)
   one_hot = tf.one_hot(label, 4)
   options = tf.stack([
       example['answer0'],
       example['answer1'],
       example['answer2'],
       example['answer3'],
   ])
   return {
       'context': example['context'],
       'question': example['question'],
       'options': options,
       'label': label,
       'answer': tf.boolean_mask(options, one_hot)[0],
   }


 def _filter_cosmos_qa(dataset):
   def my_fn(example):
     return 'label' in example
   return dataset.filter(my_fn)


 TASK_CONFIGS['cosmos_qa'] = TaskConfig(
     source=seqio.TfdsDataSource(
         tfds_name='cosmos_qa:1.0.0',
         splits={
             'train': f'train[:-{NUM_VAL_EXAMPLES}]',
             'validation': f'train[-{NUM_VAL_EXAMPLES}:]',
             'test': 'validation',
         }),
     preprocessors=[
         _filter_cosmos_qa,
         _process_cosmos_qa,
         prep.format_options,
     ],
     postprocess_fn=None,
     # Metric function from nlp/unicorn/rainbow/ext5/qa_tasks.py
     metric_fns=[t5_metrics.accuracy],
 )
```
**Expected behavior**
Download the dataset.

**Comment by pierrot0** [comment]
Hi,

Could you provide an URL of the documentation you have been using please?

The cosmos_qa dataset build directly from TFDS works just fine. It downloads the following files and then prepares the dataset from them:

```
$ md5sum raw.github.com_wilbur_cosmos_master_*
7b181e2e2fadf8e4884d9256bf11d348  raw.github.com_wilbur_cosmos_master_testcABRltwliLld408WV7JeLBpIEM_lW1uwwOFVgMN7PtA.jsonl
1b02e93b2410d22ea6720c9d9009b0b2  raw.github.com_wilbur_cosmos_master_testcABRltwliLld408WV7JeLBpIEM_lW1uwwOFVgMN7PtA.jsonl.INFO
81b8c25fde25b18f11d23bda100a6830  raw.github.com_wilbur_cosmos_master_train2NXKH59lNLZTBVBxhZGviTctl2qPxBk2D6tBWN7k0LI.csv
ff006c241a78d68bc763b2a55fcba9f7  raw.github.com_wilbur_cosmos_master_train2NXKH59lNLZTBVBxhZGviTctl2qPxBk2D6tBWN7k0LI.csv.INFO
f62387517fb799d326625b14f6c8457d  raw.github.com_wilbur_cosmos_master_validpqlPwUY8qCuxD5jvaO1TVAXm9cNuBE_44Ta1wZ3qY_M.csv
285a9be72454c2a6c80920a4814bfdf9  raw.github.com_wilbur_cosmos_master_validpqlPwUY8qCuxD5jvaO1TVAXm9cNuBE_44Ta1wZ3qY_M.csv.INFO
```

Do you have those files in your downloads directory (typically ~/tensorflow_datasets/downloads/)?

Could you run the following command directly and give the output?
The command should download and prepare the dataset directly, without going through SeqIO or flan.

```sh
tfds build cosmos_qa
```

If you don't have the cli installed: https://www.tensorflow.org/datasets/cli

Thanks,
Pierre

**Comment by conceptofmind** [comment]
Hi @pierrot0,

Here is the documentation I have been following: https://github.com/google-research/FLAN/tree/main/flan/v2

These files are in the download directory:
```
81b8c25fde25b18f11d23bda100a6830  raw.github.com_wilbur_cosmos_master_train2NXKH59lNLZTBVBxhZGviTctl2qPxBk2D6tBWN7k0LI.csv
ff006c241a78d68bc763b2a55fcba9f7  raw.github.com_wilbur_cosmos_master_train2NXKH59lNLZTBVBxhZGviTctl2qPxBk2D6tBWN7k0LI.csv.INFO
f62387517fb799d326625b14f6c8457d  raw.github.com_wilbur_cosmos_master_validpqlPwUY8qCuxD5jvaO1TVAXm9cNuBE_44Ta1wZ3qY_M.csv
285a9be72454c2a6c80920a4814bfdf9  raw.github.com_wilbur_cosmos_master_validpqlPwUY8qCuxD5jvaO1TVAXm9cNuBE_44Ta1wZ3qY_M.csv.INFO
```
These files are not in the download directory:
```
7b181e2e2fadf8e4884d9256bf11d348  raw.github.com_wilbur_cosmos_master_testcABRltwliLld408WV7JeLBpIEM_lW1uwwOFVgMN7PtA.jsonl
1b02e93b2410d22ea6720c9d9009b0b2  raw.github.com_wilbur_cosmos_master_testcABRltwliLld408WV7JeLBpIEM_lW1uwwOFVgMN7PtA.jsonl.INFO
```
When following:
```
tfds build cosmos_qa
```
Here is the full output:
```
INFO[download_manager.py]: Skipping download of https://raw.githubusercontent.com/wilburOne/cosmosqa/master/data/test.jsonl: File cached in /home/henry/tensorflow_datasets/downloads/manual/test.jsonl
INFO[download_manager.py]: Skipping download of https://raw.githubusercontent.com/wilburOne/cosmosqa/master/data/train.csv: File cached in /home/henry/tensorflow_datasets/downloads/raw.github.com_wilbur_cosmos_master_train2NXKH59lNLZTBVBxhZGviTctl2qPxBk2D6tBWN7k0LI.csv
INFO[download_manager.py]: Skipping download of https://raw.githubusercontent.com/wilburOne/cosmosqa/master/data/valid.csv: File cached in /home/henry/tensorflow_datasets/downloads/raw.github.com_wilbur_cosmos_master_validpqlPwUY8qCuxD5jvaO1TVAXm9cNuBE_44Ta1wZ3qY_M.csv
Dl Size...: 100%|██████████| 18788794/18788794 [00:00<00:00, 989303194.02 MiB/s]
Dl Completed...: 100%|█████████████████████████| 3/3 [00:00<00:00, 150.39 url/s]
INFO[writer.py]: Done writing /home/henry/tensorflow_datasets/cosmos_qa/1.0.0.incompleteU9GYWA/cosmos_qa-train.tfrecord*. Number of examples: 25262 (shards: [25262])
INFO[writer.py]: Done writing /home/henry/tensorflow_datasets/cosmos_qa/1.0.0.incompleteU9GYWA/cosmos_qa-validation.tfrecord*. Number of examples: 2985 (shards: [2985])
Traceback (most recent call last):                                              
  File "/home/henry/anaconda3/envs/palm/bin/tfds", line 8, in <module>
    sys.exit(launch_cli())
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/main.py", line 109, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/main.py", line 104, in main
    args.subparser_fn(args)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 282, in _build_datasets
    _download_and_prepare(args, builder)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/scripts/cli/build.py", line 518, in _download_and_prepare
    builder.download_and_prepare(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/logging/__init__.py", line 169, in __call__
    return function(*args, **kwargs)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 632, in download_and_prepare
    self._download_and_prepare(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1521, in _download_and_prepare
    future = split_builder.submit_split_generation(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/split_builder.py", line 341, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/core/split_builder.py", line 406, in _build_from_generator
    for key, example in utils.tqdm(
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/henry/anaconda3/envs/palm/lib/python3.9/site-packages/tensorflow_datasets/question_answering/cosmos_qa.py", line 98, in _generate_examples
    yield row['id'], row
KeyError: 'id'
```
Thank you,

Enrico

**Comment by conceptofmind** [comment]
Cosmos QA seems to build now after recent updates to tfds nightly.
