### ISSUE TITLE
Loading Dataset in Docker Container

### ISSUE THREAD

**Issue by peterdavidfagan** [tensorflow/datasets#5078]
**Short description**
I have been unable to load datasets stored in public GCP buckets into my docker container.

**Environment information**
* Operating System: Ubuntu 22.04 LTS
* Python version: 3.10
* `tensorflow-datasets`: 4.9.2
* `tensorflow`:  2.13.0

**Reproduction instructions**

Running the following and/or equivalent for another tensorflow dataset results in an error:

```python
import tensorflow_datasets as tfds
data_directory = 'gs://gresearch/robotics/language_table/0.0.1/'
dataset = tfds.builder_from_directory(data_directory).as_dataset()
```

[source](https://github.com/google-research/language-table)

**Link to logs**
```
training_jobs-jax-1  | Error executing job with overrides: ['+move_puzzle=container_single_gpu_executor_default']
training_jobs-jax-1  | Downloading dataset from GCS...
training_jobs-jax-1  | Traceback (most recent call last):
training_jobs-jax-1  |   File "/app/visual_concept_planner/single_gpu_train_executor.py", line 119, in main
training_jobs-jax-1  |     train_data, test_data = load_dataset(cfg)
training_jobs-jax-1  |   File "/app/visual_concept_planner/utils/train_utils.py", line 50, in load_dataset
training_jobs-jax-1  |     dataset = tfds.builder_from_directory(data_directory).as_dataset()
training_jobs-jax-1  |   File "/root/.cache/pypoetry/virtualenvs/visual_concept_planner-9TtSrW0h-py3.10/lib/python3.10/site-packages/tensorflow_datasets/core/read_only_builder.py", line 137, in builder_from_directory
training_jobs-jax-1  |     return ReadOnlyBuilder(builder_dir=builder_dir)
training_jobs-jax-1  |   File "/root/.cache/pypoetry/virtualenvs/visual_concept_planner-9TtSrW0h-py3.10/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py", line 288, in decorator
training_jobs-jax-1  |     return function(*args, **kwargs)
training_jobs-jax-1  |   File "/root/.cache/pypoetry/virtualenvs/visual_concept_planner-9TtSrW0h-py3.10/lib/python3.10/site-packages/tensorflow_datasets/core/read_only_builder.py", line 64, in __init__
training_jobs-jax-1  |     info_proto = dataset_info.read_proto_from_builder_dir(builder_dir)
training_jobs-jax-1  |   File "/root/.cache/pypoetry/virtualenvs/visual_concept_planner-9TtSrW0h-py3.10/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_info.py", line 985, in read_proto_from_builder_dir
training_jobs-jax-1  |     if not info_path.exists():
training_jobs-jax-1  |   File "/root/.cache/pypoetry/virtualenvs/visual_concept_planner-9TtSrW0h-py3.10/lib/python3.10/site-packages/etils/epath/gpath.py", line 131, in exists
training_jobs-jax-1  |     return self._backend.exists(self._path_str)
training_jobs-jax-1  |   File "/root/.cache/pypoetry/virtualenvs/visual_concept_planner-9TtSrW0h-py3.10/lib/python3.10/site-packages/etils/epath/backend.py", line 215, in exists
training_jobs-jax-1  |     return self.gfile.exists(path)
training_jobs-jax-1  |   File "/root/.cache/pypoetry/virtualenvs/visual_concept_planner-9TtSrW0h-py3.10/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 290, in file_exists_v2
training_jobs-jax-1  |     _pywrap_file_io.FileExists(compat.path_to_bytes(path))
training_jobs-jax-1  | RuntimeError: basic_filebuf::underflow error reading the file: Is a directory
training_jobs-jax-1  | 
training_jobs-jax-1  | Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

**Expected behavior**
Dataset to load as it does when running the same code on the host.

**Comment by fineguy** [comment]
Hi @peterdavidfagan, thanks for your interest in TFDS!

I think this error has something to do with the environment of your Docker image.

I suggest you try:
1. Rebuild the image from scratch.
1. Run https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login.
1. Run your code again.

**Comment by peterdavidfagan** [comment]
Hey @fineguy, 

Apologies for the delay in response, I have been slightly behind on my task list recently so wasn't monitoring my notifications. It did turn out to be an error within my container as you suggested 👍.
