### ISSUE TITLE
TFDS fails to import on Windows

### ISSUE THREAD

**Issue by crlishka** [tensorflow/datasets#5088]
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
Description of the bug.

**Environment information**
* Operating System: Windows (tested on Windows 11)
* Python version: 3.11, but very likely affects other Python versions
* `tensorflow-datasets`/`tfds-nightly` version: 4.9.3 (atest available on pypi.org) and 4.9.3.dev202309180044
* `tensorflow`/`tf-nightly` version: 2.13.0, installed from pypi.org

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes, see versions above

**Reproduction instructions**

```python
import tensorflow as tf
import tensorflow_datasets as tfds
```
On WIndows, the failure you will see is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\__init__.py", line 43, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\core\__init__.py", line 22, in <module>
    from tensorflow_datasets.core import community
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\core\community\__init__.py", line 18, in <module>
    from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in <module>
    from tensorflow_datasets.core import dataset_builder
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 44, in <module>
    from tensorflow_datasets.core import split_builder as split_builder_lib
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\core\split_builder.py", line 37, in <module>
    from tensorflow_datasets.core import writer as writer_lib
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\core\writer.py", line 33, in <module>
    from tensorflow_datasets.core import shuffle
  File "C:\Users\crl-sdp\work\miniconda3\envs\tfds-test-py311\Lib\site-packages\tensorflow_datasets\core\shuffle.py", line 20, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

**Expected behavior**
"import tensorflow_datasets" on Windows should work without fail.

Instead, the failure above is immediately seen because python does not include a "resource" package on Windows.  The python "resource" package is only available on Unix.  Hence, trying to "import resource" (from within tensorflow_datasets) on Windows will always fail.

**Additional context**

This issue was introduced in the following commit to the datasets repository:

commit 8f44c895c4115ac75d4c2ca4847ebf441e5450d4
Date:   Wed Aug 23 03:32:29 2023 -0700

This commit tries to fix a "too many open files" error, but the fix is Unix-specific.  The fix is not guarded to only run on Unix, so when tensorflow_datasets is imported on Windows, the Unix-specific fix causes the failure seen above.

**Comment by crlishka** [comment]
Please note previously reported issue #5075 details the same problem.  However, I opened this new issue because #5075 does not have much detail, and I am able to provide full detail in the above descripton.

**Comment by fineguy** [comment]
Thanks for bringing this issue to our attention! I hope https://github.com/tensorflow/datasets/commit/82215c7cf4b3e6df706a72c9b7ad8cede09f4d84 resolves your problem.
