### ISSUE TITLE
Cannot load huggingface:imagenet-1k dataset due to parse error

### ISSUE THREAD

**Issue by christian-steinmeyer** [tensorflow/datasets#5105]
**Short description**
When following the instructions [here](https://www.tensorflow.org/datasets/community_catalog/huggingface/imagenet-1k), I cannot download the imagenet-1k dataset from huggingface.

**Environment information**
* Operating System: macOS Sonoma 14.0 (23A344)
* Python version: 3.10.10
* `tensorflow-datasets`/`tfds-nightly` version: 4.9.3.dev202310060044
* `tensorflow`/`tf-nightly` version: 2.13.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? **Yes**

 
**Reproduction instructions**

```python
import tensorflow_datasets as tfds

if __name__ == '__main__':
    ds = tfds.load('huggingface:imagenet-1k', split='train')

```

**Stacktrace**
```shell
Traceback (most recent call last):
  File "<python_file>.py", line 4, in <module>
    ds = tfds.load('huggingface: imagenet-1k', split='train')
  File "<venv>/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py", line 168, in __call__
    return function(*args, **kwargs)
  File "<venv>/lib/python3.10/site-packages/tensorflow_datasets/core/load.py", line 633, in load
    dbuilder = _fetch_builder(
  File "<venv>/lib/python3.10/site-packages/tensorflow_datasets/core/load.py", line 488, in _fetch_builder
    return builder(name, data_dir=data_dir, try_gcs=try_gcs, **builder_kwargs)
  File "<...>/.pyenv/versions/3.10.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "<venv>/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py", line 168, in __call__
    return function(*args, **kwargs)
  File "<venv>/lib/python3.10/site-packages/tensorflow_datasets/core/load.py", line 171, in builder
    name, builder_kwargs = naming.parse_builder_name_kwargs(
  File "<venv>/lib/python3.10/site-packages/tensorflow_datasets/core/naming.py", line 141, in parse_builder_name_kwargs
    name, parsed_builder_kwargs = _dataset_name_and_kwargs_from_name_str(name)
  File "<venv>/lib/python3.10/site-packages/tensorflow_datasets/core/naming.py", line 173, in _dataset_name_and_kwargs_from_name_str
    raise ValueError(err_msg)
ValueError: Parsing builder name string huggingface: imagenet-1k failed.
The builder name string must be of the following format:
  dataset_name[/config_name][:version][/kwargs]

  Where:

    * dataset_name and config_name are string following python variable naming.
    * version is of the form x.y.z where {x,y,z} can be any digit or *.
    * kwargs is a comma list separated of arguments and values to pass to
      builder.

  Examples:
    my_dataset
    my_dataset:1.2.*
    my_dataset/config1
    my_dataset/config1:1.*.*
    my_dataset/config1/arg1=val1,arg2=val2
    my_dataset/config1:1.2.3/right=True,foo=bar,rate=1.2
```

**Expected behavior**
The parser properly parses the string given in the documentation and downloading the dataset succeeds.

**Additional context**

**Comment by ccl-core** [comment]
Hello @christian-steinmeyer !

As HF and TFDS have different naming rules, you will have to adapt the dataset name to follow TFDS' naming: in this case, the correct name would be `huggingface:imagenet_1k`

As a pointer, you can refer to the `from_hf_to_tfds` function under:
https://github.com/tensorflow/datasets/blob/3e6bec0e82809c4994a56e6926e4838a487c7688/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py#L124

We will update our documentation so that this is clearer for users!

**Comment by christian-steinmeyer** [comment]
That worked, thanks! And yes, an update in the documentation would be very helpful!

**Comment by christian-steinmeyer** [comment]
@ccl-core Quick follow-up question: Downloading the dataset worked - however, after generating splits, the `load` function also includes the step of generating tfrecords (Output "Generating training examples..."), which is pretty slow for me (~20 examples/s). Is there any way to speed this up? I couldn't find anything in the builder config or the download and prepare config. The number of available CPUs doesn't seem to be a factor. For Imagenet-1k, this is taking many hours.

**Comment by maziarzamani** [comment]
> @ccl-core Quick follow-up question: Downloading the dataset worked - however, after generating splits, the `load` function also includes the step of generating tfrecords (Output "Generating training examples..."), which is pretty slow for me (~20 examples/s). Is there any way to speed this up? I couldn't find anything in the builder config or the download and prepare config. The number of available CPUs doesn't seem to be a factor. For Imagenet-1k, this is taking many hours.

Same problem here. It runs ~20 examples/s and eventually after a day or so it crashes.
