### ISSUE TITLE
Can not load robotics dataset

### ISSUE THREAD

**Issue by yepw** [tensorflow/datasets#5295]
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
Could not load robotics datasets such as `berkeley_autolab_ur5`

**Environment information**
* Operating System: Ubuntu 
* Python version:  3.8
* `tensorflow-datasets`/`tfds-nightly` version: nightly 4.9.2.dev202308090034
* `tensorflow`/`tf-nightly` version: tensorflow 2.13.1

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes

**Reproduction instructions**
```python
import tensorflow_datasets as tfds
import tensorflow as tf

tfds = tfds.load('berkeley_autolab_ur5')
```

**Expected behavior**
It starts downloading the dataset.

**Actual behavior**
```
Traceback (most recent call last):
  File "dataset.py", line 11, in <module>
    tfds = tfds.load('berkeley_autolab_ur5')
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/logging/__init__.py", line 166, in __call__
    return function(*args, **kwargs)
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 633, in load
    dbuilder = _fetch_builder(
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 488, in _fetch_builder
    return builder(name, data_dir=data_dir, try_gcs=try_gcs, **builder_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/logging/__init__.py", line 166, in __call__
    return function(*args, **kwargs)
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 215, in builder
    raise not_found_error
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 196, in builder
    cls = builder_cls(str(name))
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/load.py", line 121, in builder_cls
    cls = registered.imported_builder_cls(str(ds_name))
  File "/home/yepw/.local/lib/python3.8/site-packages/tensorflow_datasets/core/registered.py", line 301, in imported_builder_cls
    raise DatasetNotFoundError(f'Dataset {name} not found.')
tensorflow_datasets.core.registered.DatasetNotFoundError: Dataset berkeley_autolab_ur5 not found.
Available datasets:
        - abstract_reasoning
        - accentdb
        - aeslc
        - aflw2k3d
        - ag_news_subset
        - ai2_arc
        ...
       - youtube_vis

Check that:
    - if dataset was added recently, it may only be available
      in `tfds-nightly`
    - the dataset name is spelled correctly
    - dataset class defines all base class abstract methods
    - the module defining the dataset class is imported

The builder directory /home/yepw/tensorflow_datasets/berkeley_autolab_ur5 doesn't contain any versions.
No builder could be found in the directory: /home/yepw/tensorflow_datasets for the builder: berkeley_autolab_ur5.
No registered data_dirs were found in:
        - /home/yepw/tensorflow_datasets
```

**Comment by marcenacp** [comment]
Hi @yepw, are you sure you use the latest version of TFDS? I could successfully start downloading the dataset with:

```python
$ git clone git@github.com:tensorflow/datasets.git
$ cd datasets
$ pip install -e .
$ python -c "import tensorflow_datasets as tfds; tfds = tfds.load('berkeley_autolab_ur5')"
Downloading and preparing dataset Unknown size (download: Unknown size, generated: 76.39 GiB, total: 76.39 GiB) to /usr/local/google/home/pierremarcenac/tensorflow_datasets/berkeley_autolab_ur5/0.1.0...
```

**Comment by marcenacp** [comment]
Closing the PR, feel free to re-open if the problem persists. :)

**Comment by yepw** [comment]
After updating Tensorflow, the error was fixed, but I encountered another error: https://github.com/tensorflow/datasets/issues/5360
