### ISSUE TITLE
tfds build failed

### ISSUE THREAD

**Issue by CharlieLi2S** [tensorflow/datasets#5329]
**What I need help with / What I was wondering**
I am trying to build a dataset using tfds build, while this error occured: TypeError: Unknown resource path: <class 'importlib_resources.readers.MultiplexedPath'>: MultiplexedPath('/home/language_table_use')
> root@15298479e1f0:/home/language_table_use# tfds build
INFO[build.py]: Loading dataset  from path: /home/language_table_use/language_table_use_dataset_builder.py
2024-03-20 10:09:39.534800: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-20 10:09:39.577882: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-20 10:09:39.577940: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-20 10:09:39.577973: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-20 10:09:39.586478: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/usr/local/bin/tfds", line 8, in <module>
    sys.exit(launch_cli())
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/scripts/cli/main.py", line 103, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.11/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/scripts/cli/main.py", line 98, in main
    args.subparser_fn(args)
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/scripts/cli/build.py", line 311, in _build_datasets
    for builder in builders:
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/scripts/cli/build.py", line 362, in _make_builders
    yield make_builder()
          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/scripts/cli/build.py", line 477, in _make_builder
    builder = builder_cls(**builder_kwargs)  # pytype: disable=not-instantiable
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/language_table_use/language_table_use_dataset_builder.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/logging/__init__.py", line 288, in decorator
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1319, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/logging/__init__.py", line 288, in decorator
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 287, in __init__
    self.info.initialize_from_bucket()
    ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/logging/__init__.py", line 168, in __call__
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 476, in info
    info = self._info()
           ^^^^^^^^^^^^
  File "/home/language_table_use/language_table_use_dataset_builder.py", line 24, in _info
    return self.dataset_info_from_configs(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1098, in dataset_info_from_configs
    metadata = self.get_metadata()
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 245, in get_metadata
    return dataset_metadata.load(cls._get_pkg_dir_path())
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 235, in _get_pkg_dir_path
    cls.pkg_dir_path = _get_builder_datadir_path(cls)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 150, in _get_builder_datadir_path
    return epath.resource_path(pkg_names[0]).joinpath(*pkg_names[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/etils/epath/resource_utils.py", line 148, in resource_path
    raise TypeError(f'Unknown resource path: {type(path)}: {path}')
TypeError: Unknown resource path: <class 'importlib_resources.readers.MultiplexedPath'>: MultiplexedPath('/home/language_table_use')

**Environment information**
(if applicable)
* Operating System: Ubuntu 22.04.2 LTS
* Python version: Python 3.11.0rc1
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 4.9.4
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow 2.14.0

**Comment by Conchylicultor** [comment]
Do you have a reproductible example ? What's you Python setup so `importlib.resources.files()` return `MultiplexedPath`. It's the first time I see this class appear.

Can you also try https://github.com/google/etils/pull/589 to see if this fix your issue ?

**Comment by CharlieLi2S** [comment]
the issue is fixed after trying https://github.com/google/etils/pull/589#issue-2197710449, thanks a lot
while a new issue occurs https://github.com/tensorflow/datasets/issues/5330#issue-2199088338
