### ISSUE TITLE
huggingface_utils.py Data type error : [AttributeError]: 'DatasetInfo' object has no attribute 'lower'

### ISSUE THREAD

**Issue by helloSir32** [tensorflow/datasets#5730]
**Short description**
huggingface_utils.py Data type error : [AttributeError]: 'DatasetInfo' object has no attribute 'lower'.

**Environment information**
* Operating System: Windows11
* Python version: 3.12
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow_datasets-4.9.7

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? dont know

**Reproduction instructions**

```python
import tensorflow_datasets as tfds
ds = tfds.load('huggingface:hippocorpus')
```

**Link to logs**
Traceback (most recent call last):
  File "F:\GraduateDesign\story_narrative_flow\test.py", line 3, in <module>
    ds = tfds.load('huggingface:hippocorpus')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\logging\__init__.py", line 176, in __call__
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\load.py", line 655, in load
    dbuilder = _fetch_builder(
               ^^^^^^^^^^^^^^^
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\load.py", line 497, in _fetch_builder
    return builder(name, data_dir=data_dir, try_gcs=try_gcs, **builder_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Environment\python\python3.12\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\logging\__init__.py", line 176, in __call__
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\load.py", line 191, in builder
    return huggingface_dataset_builder.builder(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\dataset_builders\huggingface_dataset_builder.py", line 520, in builder
    hf_repo_id = huggingface_utils.to_huggingface_name(name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\utils\huggingface_utils.py", line 142, in to_huggingface_name
    conversion_utils.to_tfds_name(hf_dataset_name)
  File "F:\GraduateDesign\story_narrative_flow\.venv\Lib\site-packages\tensorflow_datasets\core\utils\conversion_utils.py", line 49, in to_tfds_name
    name = name.lower().replace('/', '__')
           ^^^^^^^^^^
AttributeError: 'DatasetInfo' object has no attribute 'lower'

**Expected behavior**
The dataset should load.
And conversion_utils.to_tfds_name(hf_dataset_name) in huggingface_utils.py should be given a string type but a DatasetInfo which is given by huggingface_hub.list_datasets().

**Comment by fylux** [comment]
Sorry the dataset hippocorpus is not available anymore, the documentation is outdated apparently.
