### ISSUE TITLE
[data request] QMNIST Dataset

### ISSUE THREAD

**Issue by prabhuomkar** [tensorflow/datasets#624]
* Name of dataset: QMNIST
* URL of dataset: https://github.com/facebookresearch/qmnist
* License of dataset: BSD License
* Short description of dataset and use case(s):
The QMNIST dataset was generated from the original data found in the NIST Special Database 19 with the goal to match the MNIST preprocessing as closely as possible.
The exact preprocessing steps used to construct the MNIST dataset have long been lost. This leaves us with no reliable way to associate its characters with the ID of the writer and little hope to recover the full MNIST testing set that had 60K images but was never released. The official MNIST testing set only contains 10K randomly sampled images and is often considered too small to provide meaninful confidence intervals.
* MORE: <img width="582" alt="Screenshot 2019-06-01 at 9 46 48 AM" src="https://user-images.githubusercontent.com/31627958/58743592-330a2b80-8452-11e9-990c-e42348b75287.png">

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

**PS: I would like to contribute with this dataset!**

**Comment by Eshan-Agarwal** [comment]
Hello, I love to work on this issue can you please assign me this.

**Comment by prabhuomkar** [comment]
Hey sure, go ahead. It's yours. Send a PR and reference this issue.

**Comment by Eshan-Agarwal** [comment]
okay ! I am working on it.

**Comment by Eshan-Agarwal** [comment]
Hey ! I am getting some error when I am following this instruction by tensorfow on [here ](https://www.tensorflow.org/datasets/add_dataset#overview)

After cloning repository I am run this code 
`python tensorflow_datasets/scripts/create_new_dataset.py \
  --dataset my_dataset \
  --type image  # text, audio, translation,...`

And Got error : 

> Traceback (most recent call last):
  File "tensorflow_datasets/scripts/create_new_dataset.py", line 241, in <module>
    app.run(main)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tensorflow_datasets/scripts/create_new_dataset.py", line 222, in main
    dataset_cls=naming.snake_to_camelcase(dataset_name),
  File "C:\Users\eshan\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_datasets\core\naming.py", line 37, in snake_to_camelcase
    return "".join(n.capitalize() for n in name.split("_"))
AttributeError: 'NoneType' object has no attribute 'split'

How to resolve it.

**Comment by Eshan-Agarwal** [comment]
Hey ! I completed my work, can I send you PR ?

**Comment by Eshan-Agarwal** [comment]
Hey here is my PR #1535. 
Thanks !

**Comment by Eshan-Agarwal** [comment]
Please have a look I update and correct it and linting is passed
