### ISSUE TITLE
Transformer Example fails while mapping dataset

### ISSUE THREAD

**Issue by wesboyt** [tensorflow/datasets#693]
The transformer example which was updated to beta1 was working on alpha and is now failing.
AttributeError: 'str' object has no attribute 'numpy'
from:
tokenizer_en = tfds.features.text.SubwordTextEncoder.build_from_corpus(
    (en.numpy() for pt, en in train_examples), target_vocab_size=2**13)

tokenizer_pt = tfds.features.text.SubwordTextEncoder.build_from_corpus(
    (pt.numpy() for pt, en in train_examples), target_vocab_size=2**13)

**Environment information**
* Operating System: Ubuntu18.04
* Python version: 3.6
* both tensorflow-datasets and tfds-nightly's most recent editions have the same error message.
* `tensorflow-gpu version beta1

**Reproduction instructions**
run the example from here: https://www.tensorflow.org/beta/tutorials/text/transformer
changing no code except the print statements to 3.6 compatibility 

**Link to logs**
2019-06-19 08:04:30.740969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2327 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/wes/PycharmProjects/poker/language.py", line 17, in <module>
    (en.numpy() for pt, en in train_examples), target_vocab_size=2**13)
  File "/home/wes/PycharmProjects/poker/venv/lib/python3.6/site-packages/tensorflow_datasets/core/features/text/subword_text_encoder.py", line 293, in build_from_corpus
    reserved_tokens=reserved_tokens)
  File "/home/wes/PycharmProjects/poker/venv/lib/python3.6/site-packages/tensorflow_datasets/core/features/text/subword_text_encoder.py", line 395, in _token_counts_from_generator
    for s in generator:
  File "/home/wes/PycharmProjects/poker/language.py", line 17, in <genexpr>
    (en.numpy() for pt, en in train_examples), target_vocab_size=2**13)
AttributeError: 'str' object has no attribute 'numpy'

**Expected behavior**
Get back a list of tensors(debugging I can see that the list of tensors exists and reflects the actual dataset) , instead you just get 'en', 'pt' every iteration

**Comment by wesboyt** [comment]
Upon clearing out my datasets folder and reinstalling tfds I'm back to functional, seems like an issue on my end!
