### ISSUE TITLE
Loading "super_glue/copa" fails

### ISSUE THREAD

**Issue by craffel** [tensorflow/datasets#797]
**Short description**
The following:
```Python
import tensorflow_datasets as tfds
tfds.load("super_glue/copa")
```
fails on Google Cloud with the error
```Python
ValueError: Trying to overwrite already defined ClassLabel names. Previous: ['choice1', 'choice2'] , new: ['False', 'True']
```

**Environment information**
* Operating System: Debian GNU/Linux 9.9 on GCloud VM
* Python version: 3.7.4
* `tensorflow-datasets`/`tfds-nightly` version: Cloned from GitHub.
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 1.14.0

**Reproduction instructions**

```Python
import tensorflow_datasets as tfds
tfds.load("super_glue/copa")
```

**Link to logs**

```
E0720 17:33:57.960958 140060231877888 registered.py:171] Failed to construct dataset super_glue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/registered.py", line 296, in load
    dbuilder = builder(name, data_dir=data_dir, **builder_kwargs)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/registered.py", line 169, in builder
    return _DATASET_REGISTRY[name](**builder_kwargs)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/dataset_builder.py", line 188, in __init__
    self.info.initialize_from_bucket()
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/dataset_info.py", line 412, in initialize_from_bucket
    self.read_from_directory(tmp_dir)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/dataset_info.py", line 353, in read_from_directory
    self.features.load_metadata(dataset_info_dir)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/features/features_dict.py", line 227, in load_metadata
    feature.load_metadata(data_dir, feature_name=feature_key)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/features/class_label_feature.py", line 160, in load_metadata
    self.names = _load_names_from_file(names_filepath)
  File "/home/craffel/.pyenv/versions/transformer/lib/python3.7/site-packages/tensorflow_datasets-1.0.2-py3.7.egg/tensorflow_datasets/core/features/class_label_feature.py", line 84, in names
    ", new: {}".format(self._int2str, int2str))
ValueError: Trying to overwrite already defined ClassLabel names. Previous: ['choice1', 'choice2'] , new: ['False', 'True']
```

**Expected behavior**
The dataset would load.

**Additional context**
Installed by cloning GitHub repo and running `python setup.py install` at commit d89aeb9a9ae2ba7d470eb54743998ad6ce528544

**Comment by craffel** [comment]
The file at
http://storage.googleapis.com/tfds-data/dataset_info/super_glue/copa/0.0.2/label.labels.txt
is out-of-date. This commit: https://github.com/tensorflow/datasets/commit/bd4dcb3770950edecbe423d3470880664047fe5b#diff-d1805548908d5fc91f4336f075fc77cc changed the `label_names` to `["choice1", "choice2"]` but the file label.labels.txt file still lists them as "False" and "True". Can the label.labels.txt file be updated? @adarob

**Comment by us** [comment]
@craffel Thanks for reporting! 

@Conchylicultor I think we need to pre-computing this dataset for gcs.

**Comment by Conchylicultor** [comment]
I deleted the GCS files so which should fix the issue. They will be automatically re-generated with the right values today.

**Comment by Conchylicultor** [comment]
I deleted the GCS files so which should fix the issue. They will be automatically re-generated with the right values today.

**Comment by Conchylicultor** [comment]
I deleted the GCS files so which should fix the issue. They will be automatically re-generated with the right values today.

**Comment by craffel** [comment]
http://storage.googleapis.com/tfds-data/dataset_info/super_glue/ does not exist yet. Any way to monitor when it will be regenerated?

**Comment by Conchylicultor** [comment]
Dataset should works anyway no ? It's just that external users will regenerate the dataset_info.json themselves instead of pre-loading it.
Otherwise, our auto-gen script run at noon today.

**Comment by craffel** [comment]
> Dataset should works anyway no ?

Since the info json doesn't exist, the splits don't get populated, so not really.

https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_builder.py#L183

**Comment by Conchylicultor** [comment]
Oh, because you already generated the dataset. Once the dataset is generated, it load from `data_dir` anyway, not GCS.
Regenerating the data should works
