### ISSUE TITLE
Huggingface dataset supporting issue

### ISSUE THREAD

**Issue by beiningwu7** [tensorflow/datasets#9014]
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
Unable to load huggingface datasets with the tfds.load() function. 

**Environment information**
* Operating System: Debian 6.1.99-1 (2024-07-15) x86_64
* Python version: 3.11
* `tensorflow-datasets`/`tfds-nightly` version: 4.9.7
* `tensorflow`/`tf-nightly` version: 2.18.0
* `datasets` version: 3.1.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) Yes

**Reproduction instructions**

```python
import tensorflow_datasets as tfds
tfds.load('huggingface:openwebtext/plain_text')
```

**Logs**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/logging/__init__.py", line 176, in __call__
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/load.py", line 650, in load
    dbuilder = _fetch_builder(
               ^^^^^^^^^^^^^^^
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/load.py", line 492, in _fetch_builder
    return builder(name, data_dir=data_dir, try_gcs=try_gcs, **builder_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/logging/__init__.py", line 176, in __call__
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/load.py", line 188, in builder
    return huggingface_dataset_builder.builder(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py", line 520, in builder
    hf_repo_id = huggingface_utils.to_huggingface_name(name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/utils/huggingface_utils.py", line 144, in to_huggingface_name
    conversion_utils.to_tfds_name(hf_dataset_name)
  File "/home-nfs/beiningw/miniconda/envs/jax/lib/python3.11/site-packages/tensorflow_datasets/core/utils/conversion_utils.py", line 49, in to_tfds_name
    name = name.lower().replace('/', '__')
           ^^^^^^^^^^
AttributeError: 'DatasetInfo' object has no attribute 'lower'

**Expected behavior**
By [https://www.tensorflow.org/datasets/community_catalog/huggingface/openwebtext](url), the tfds module can load the dataset from huggingface directly. 

**Additional context**

**Comment by fineguy** [comment]
@beiningwu7 thanks for notifying us about this issue! It should be fixed in https://github.com/tensorflow/datasets/commit/8807a05b89fee7c2e1b764bda3927320fe53d944
